guacsec/trustify

- .github/workflows/backend.yaml
- backend/rust-toolchain.toml
This is the egg belonging to the chicken named #1
> add github workflow for backend

- backend/importer/Cargo.toml
- backend/importer/src/csaf/mod.rs
- backend/importer/src/sbom/mod.rs
Just trying to bring this to the most recent API
> chore: update to most recent version

- frontend/README.md
- frontend/package.json
Fixes https://github.com/trustification/trustify/issues/12
> Remove kubectl commands as it is early to integrate the UI to remote k8s-backend

- graph/src/graph/advisory/mod.rs
- graph/src/graph/mod.rs
- server/Cargo.toml
- server/src/lib.rs
- server/src/server/importer/endpoints.rs
- server/src/server/importer/mod.rs
- server/src/server/importer/model.rs
- server/src/server/importer/service.rs
- server/src/server/importer/test.rs
- server/src/server/mod.rs
> feat: implement API for importer, based on mock backend

- etc/test-data/osv/RUSTSEC-2021-0079.json
- etc/test-data/osv/RUSTSEC-2022-0022.json
- graph/src/graph/vulnerability.rs
- ingestors/src/advisory/mod.rs
- ingestors/src/advisory/osv/loader.rs
- ingestors/src/advisory/osv/mod.rs
- ingestors/src/advisory/osv/schema.rs
- ingestors/src/cve/loader.rs
> Enable rough parsing and ingesting of OSV-schema advisory documents.

- graph/src/graph/advisory/csaf/mod.rs
- graph/src/graph/advisory/mod.rs
- graph/src/graph/package/mod.rs
- graph/src/graph/package/package_version.rs
- graph/src/graph/package/qualified_package.rs
- graph/src/graph/sbom/mod.rs
- graph/src/graph/vulnerability/mod.rs
- ingestors/src/advisory/osv/loader.rs
- ingestors/src/advisory/osv/schema.rs
- ingestors/src/cve/loader.rs
Ingest OSV more fully to track affected/fixed details.
> Improve relationship between Advisory and Vulnerability.

- entity/src/cvss3.rs
- entity/src/cvss4.rs
- entity/src/lib.rs
- migration/src/lib.rs
- migration/src/m0000002_create_cvss4_enums.rs
- migration/src/m0000034_create_cvss4.rs
Does not currently use these entities, but...
* Creates entity objects (activemodel, etc)
* Creates relevant enums in the DB.
* Creates relevant table in the DB.
> Cvss4 entities

- modules/ingestor/src/endpoints/advisory.rs
- modules/ingestor/src/service/advisory/mod.rs
- modules/ingestor/src/service/mod.rs
> Add UnsupportedFormat error to affirm existing logic

- modules/ingestor/src/service/advisory/csaf/loader.rs
- modules/ingestor/src/service/advisory/csaf/mod.rs
- modules/ingestor/src/service/advisory/osv/loader.rs
> Pass the loaders a checksum to verify file integrity

- modules/ingestor/src/service/advisory/csaf/mod.rs
- modules/ingestor/src/service/advisory/mod.rs
> refactor: loader delegation in Format::load now

- modules/search/src/query.rs
Resolves #148
In doing so, I realized the `!=` operator was broken for multi-values, so instead of being OR'd together, the multi-values for NOT ops (!=, !~) are AND'd. I included that fix in here as well.
> feat: add a NotLike operator, `!~`

- modules/graph/src/graph/package/mod.rs
- modules/graph/src/graph/sbom/spdx/tests/mod.rs
- modules/graph/src/graph/sbom/spdx/tests/perf.rs
* Update the large test, make it work again
* Add an example demonstrating the search for JSON child elements
* enable test_log::test for more tests
> Tweak tests

- modules/graph/src/graph/sbom/mod.rs
- modules/graph/src/graph/vulnerability/mod.rs
- modules/search/src/endpoints.rs
- modules/search/src/query.rs
- modules/search/src/service.rs
> refactor the filtering logic into a single `filtering` fn

- modules/graph/src/graph/advisory/advisory_vulnerability.rs
- modules/graph/src/graph/advisory/affected_package_version_range.rs
- modules/graph/src/graph/advisory/fixed_package_version.rs
- modules/graph/src/graph/advisory/mod.rs
- modules/graph/src/graph/advisory/not_affected_package_version.rs
- modules/graph/src/graph/package/mod.rs
- modules/graph/src/graph/package/package_version.rs
- modules/graph/src/graph/package/package_version_range.rs
- modules/graph/src/graph/package/qualified_package.rs
- modules/graph/src/graph/sbom/mod.rs
- modules/graph/src/graph/vulnerability/mod.rs
graph Contexts.
In preparation to split `graph` into better-organized parts.
> Remove the terribly too clever usage of `From<...>` for the various

- cvss/src/cvss3/mod.rs
- cvss/src/cvss3/score.rs
- cvss/src/cvss3/severity.rs
- cvss/src/lib.rs
- modules/graph/src/endpoints/advisory.rs
- modules/graph/src/endpoints/mod.rs
- modules/graph/src/graph/advisory/advisory_vulnerability.rs
- modules/graph/src/graph/advisory/affected_package_version_range.rs
- modules/graph/src/model/advisory.rs
Ensure CVSS3 scores actually surface to the details
- fix bug related to fetching CVSS3 scores.
> Provide list of relevant vulnerability IDs in advisory summaries.

- common/src/db/test.rs
- modules/ingestor/src/graph/sbom/tests.rs
> The TempDir must live as long as the PostgreSQL instance, duh

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/db/mod.rs
- common/src/db/test.rs
- entity/src/qualified_package.rs
- migration/src/m0000120_create_package_version.rs
- migration/src/m0000130_create_qualified_package.rs
- modules/fetch/Cargo.toml
- modules/fetch/src/service.rs
- modules/importer/src/server/sbom/mod.rs
- modules/importer/src/server/sbom/storage.rs
- modules/ingestor/Cargo.toml
- modules/ingestor/src/graph/advisory/advisory_vulnerability.rs
- modules/ingestor/src/graph/advisory/mod.rs
- modules/ingestor/src/graph/mod.rs
- modules/ingestor/src/graph/package/mod.rs
- modules/ingestor/src/graph/package/package_version.rs
- modules/ingestor/src/graph/package/qualified_package.rs
- modules/ingestor/src/graph/sbom/mod.rs
- modules/ingestor/src/graph/sbom/spdx/mod.rs
- modules/ingestor/src/graph/sbom/spdx/tests/mod.rs
- modules/ingestor/src/graph/sbom/spdx/tests/perf.rs
- modules/ingestor/src/graph/sbom/tests.rs
- modules/ingestor/src/service/advisory/csaf/loader.rs
- modules/ingestor/src/service/advisory/osv/loader.rs
Baseline:
```
[INFO  trustify_module_ingestor::graph::sbom::spdx::tests::perf] parse: 2s 641ms 659us 474ns
[INFO  trustify_module_ingestor::graph::sbom::spdx::tests::perf] ingest 1: 2ms 413us 634ns
[INFO  trustify_module_ingestor::graph::sbom::spdx::tests::perf] ingest 2: 14s 688ms 183us 212ns
[INFO  trustify_module_ingestor::graph::sbom::spdx::tests::perf] commit: 390us 927ns
[INFO  trustify_module_ingestor::graph::sbom::spdx::tests::perf] query: 4ms 109us 506ns
test graph::sbom::spdx::tests::perf::ingest_spdx_medium ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 43 filtered out; finished in 18.87s
```
This PR:
```
2024-04-26T14:07:32.672525Z  INFO trustify_module_ingestor::graph::sbom::spdx::tests::perf: parse: 2s 492ms 106us 342ns    
2024-04-26T14:07:32.672536Z …
```
> Improve performance

- modules/ingestor/src/graph/sbom/cache.rs
- modules/ingestor/src/graph/sbom/mod.rs
- modules/ingestor/src/graph/sbom/spdx/mod.rs
- modules/ingestor/src/graph/sbom/tests.rs
Baseline:
```
2024-04-26T14:07:32.672525Z  INFO trustify_module_ingestor::graph::sbom::spdx::tests::perf: parse: 2s 492ms 106us 342ns    
2024-04-26T14:07:32.672536Z  INFO trustify_module_ingestor::graph::sbom::spdx::tests::perf: ingest 1: 2ms 564us 988ns    
2024-04-26T14:07:32.672546Z  INFO trustify_module_ingestor::graph::sbom::spdx::tests::perf: ingest 2: 12s 226ms 606us 90ns    
2024-04-26T14:07:32.672555Z  INFO trustify_module_ingestor::graph::sbom::spdx::tests::perf: commit: 385us 427ns    
2024-04-26T14:07:32.672569Z  INFO trustify_module_ingestor::graph::sbom::spdx::tests::perf: query: 4ms 289us 159ns    
test graph::sbom::spdx::tests::perf::ingest_spdx_medium ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 43 filtered out; finished in 16.23s
```
With this PR: …
> chore: collect relationships so they can be batch inserted

- common/src/config.rs
- common/src/db/test.rs
> run tests against EXTERNAL_TEST_DB if set

- modules/search/src/query.rs
> Handle empty search criteria betterer

- Cargo.lock
- common/src/db/limiter.rs
- entity/Cargo.toml
- entity/src/lib.rs
- entity/src/package_relates_to_package.rs
- entity/src/relationship.rs
- entity/src/sbom.rs
- entity/src/sbom_package.rs
- migration/src/lib.rs
- migration/src/m0000250_create_sbom_package.rs
- modules/fetch/src/endpoints/mod.rs
- modules/fetch/src/endpoints/sbom.rs
- modules/fetch/src/model/sbom.rs
- modules/fetch/src/service/mod.rs
- modules/fetch/src/service/sbom.rs
- modules/importer/README.md
- modules/ingestor/src/graph/package/creator.rs
- modules/ingestor/src/graph/sbom/mod.rs
- modules/ingestor/src/graph/sbom/spdx/mod.rs
- modules/ingestor/src/graph/sbom/spdx/tests/perf.rs
As we don't seem to have an "describing packages", refactor the function to allow retrieving all packages.
> Allow fetching all packages from the SBOM

- common/src/config.rs
> fix: using default password for PM mode

- common/src/config.rs
This reverts commit 67e94c3a2ad55cde972aae9df1721423a83cbbd4.
> Revert "fix: using default password for PM mode"

- modules/ingestor/src/graph/sbom/tests.rs
- modules/search/src/query.rs
> Make full-text and "like" searches case-insensitive 

- Cargo.lock
- Cargo.toml
The first official release that includes our merge fix
> Bump utoipa dep to latest release, 4.2.3

- docs/glossary.md
- entity/src/advisory.rs
- entity/src/advisory_vulnerability.rs
- entity/src/vulnerability.rs
- modules/fetch/src/endpoints/vulnerability.rs
- modules/fetch/src/service/vulnerability.rs
Adjust relationships between vulnerability and advisory join table. Add tests for each endpoint.
> Fix for #237

- Cargo.lock
- Cargo.toml
- modules/fetch/Cargo.toml
- modules/fetch/src/endpoints/advisory.rs
- modules/fetch/src/service/advisory.rs
- modules/ingestor/Cargo.toml
- modules/ingestor/src/service/cve/loader.rs
- modules/ingestor/src/service/format.rs
- modules/storage/Cargo.toml
- server/Cargo.toml
Fixes #251
Also preferring urlencoding crate to url-escape
>  Add some testing of advisory searching to verify TC-894

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- modules/ui/Cargo.toml
- modules/ui/src/endpoints.rs
- modules/ui/src/lib.rs
- server/Cargo.toml
- server/src/lib.rs
Pending merging (and un-forking) of https://github.com/trustification/trustify-ui/pull/13
> Attempt to use trustify-ui as a crate dependency.

- Cargo.toml
- modules/ui/Cargo.toml
- modules/ui/src/endpoints.rs
- modules/ui/src/lib.rs
- server/Cargo.toml
- server/src/lib.rs
- trustd/Cargo.toml
To build w/o the ui:
cargo build -p trustify-trustd --no-default-features
> Put UI behind a default feature.

- modules/fetch/src/query.rs
Fixes #267
All columns in composite keys will be added to the statement if not already present.
> fix: ensure order using primary keys, not hardcoded id fields

- modules/fetch/src/query.rs
Relates to #289
Removes dependency on trustify-entity crate
> Let query tests operate on their own Entity

- integration-tests/src/sbom/test/basic.rs
- integration-tests/src/sbom/test/mod.rs
- integration-tests/src/sbom/test/perf.rs
- modules/fetch/src/service/sbom.rs
This clean up a few things that should've been in the other PR.
On the topic of the `integration-test` stuff, I am ok with this moving elsewhere. It was just necessary to get everything together.
> chore: clean up a few things

- Cargo.lock
- modules/importer/src/model/mod.rs
- modules/importer/src/test.rs
- trustd/Cargo.toml
- trustd/src/main.rs
Also, add a description field.
@carlosthe19916 the description field might be useful for the UI
> feat: provide some default/sample data for PM mode

- common/src/db/query.rs
- modules/advisory/src/endpoints/mod.rs
- modules/advisory/src/service/mod.rs
- modules/advisory/src/service/test.rs
- modules/fetch/src/endpoints/sbom.rs
- modules/fetch/src/service/sbom.rs
- modules/vulnerability/src/endpoints/mod.rs
- modules/vulnerability/src/service/mod.rs
> Some convenience fn's for query, some renaming, and docs

- server/src/lib.rs
> Fix broken download links

- .github/workflows/release.yaml
Resolves #288
Taken from https://dzfrias.dev/blog/deploy-rust-cross-platform-github-actions/
> Attempting to publish cross-platform binaries

- docs/glossary.md
> A note about SBOM's

- Cargo.lock
- migration/Cargo.toml
- migration/src/main.rs
```
➜  debug git:(migration-tokio) ✗ DATABASE_URL="postgres://postgres:eggs@localhost:5432/trustify" ./trustify-migration
Applying all pending migrations
Applying migration 'm0000010_create_cvss3_enums'
Migration 'm0000010_create_cvss3_enums' has been applied
Applying migration 'm0000020_create_cvss4_enums'
Migration 'm0000020_create_cvss4_enums' has been applied
Applying migration 'm0000022_create_organization'
Migration 'm0000022_create_organization' has been applied
Applying migration 'm0000030_create_sbom'
Migration 'm0000030_create_sbom' has been applied
Applying migration 'm0000040_create_vulnerability'
Migration 'm0000040_create_vulnerability' has been applied
Applying migration 'm0000050_create_vulnerability_description'
Migration 'm0000050_create_vulnerability_description' has …
```
> chore: sea orm migration cli using tokio - async-std removed

- common/infrastructure/src/tracing.rs
Fixes #302
For a very broad definition of "fixes".
Also gives us a straightforward way of setting other logging options as default.
> Nobody else seems to use utoipa-swagger-ui with actix-web-prom

- trustd/src/main.rs
- trustd/src/sample_data.rs
basic extraction for better (main.rs) reading, delegating that responsibility to other file/mod
> chore: extracts sample_data

- Cargo.lock
- common/Cargo.toml
- common/auth/Cargo.toml
- common/infrastructure/Cargo.toml
- cvss/Cargo.toml
- entity/Cargo.toml
- integration-tests/Cargo.toml
- migration/Cargo.toml
- modules/fundamental/Cargo.toml
- modules/importer/Cargo.toml
- modules/ingestor/Cargo.toml
- modules/storage/Cargo.toml
- modules/ui/Cargo.toml
- server/Cargo.toml
- trustd/Cargo.toml
Also: uptick for a new release
> build: fix aarch64 build when vendoring

- Cargo.lock
- Cargo.toml
- README.md
- common/Cargo.toml
- common/auth/Cargo.toml
- common/infrastructure/Cargo.toml
- cvss/Cargo.toml
- entity/Cargo.toml
- integration-tests/Cargo.toml
- migration/Cargo.toml
- modules/fundamental/Cargo.toml
- modules/importer/Cargo.toml
- modules/ingestor/Cargo.toml
- modules/storage/Cargo.toml
- modules/ui/Cargo.toml
- server/Cargo.toml
- server/src/lib.rs
- trustd/Cargo.toml
Also: uptick to next release version
> Fix PM mode auth setting when using embedded OIDC

- server/src/embedded_oidc.rs
SwaggerUI needs an additional redirect URL. This adds it.
> fix: allow swaggerui to redirect

- .github/workflows/release.yaml
- Cargo.lock
- common/Cargo.toml
- common/auth/Cargo.toml
- common/infrastructure/Cargo.toml
- cvss/Cargo.toml
- entity/Cargo.toml
- integration-tests/Cargo.toml
- migration/Cargo.toml
- modules/fundamental/Cargo.toml
- modules/importer/Cargo.toml
- modules/ingestor/Cargo.toml
- modules/storage/Cargo.toml
- modules/ui/Cargo.toml
- server/Cargo.toml
- trustd/Cargo.toml
> fix: push multi-arch image (and uptick version)

- .github/workflows/release.yaml
- README.md
- trustd/Cargo.toml
Also removing `ui` feature as I think it's just static content now.
> Make PM mode the default

- README.md
> docs: update pm mode instructions

- modules/importer/src/server/mod.rs
> fix: reset all jobs when starting up

- docs/design/products.md
- entity/src/lib.rs
- entity/src/organization.rs
- entity/src/product.rs
- entity/src/product_version.rs
- migration/src/lib.rs
- migration/src/m0000290_create_product.rs
- migration/src/m0000300_create_product_version.rs
- modules/fundamental/src/lib.rs
- modules/fundamental/src/product/mod.rs
- modules/fundamental/src/product/model/mod.rs
- modules/fundamental/src/product/model/summary.rs
- modules/fundamental/src/product/service/mod.rs
- modules/fundamental/src/product/service/test.rs
- modules/ingestor/src/graph/mod.rs
- modules/ingestor/src/graph/product/mod.rs
- modules/ingestor/src/graph/product/product_version.rs
- modules/ingestor/src/graph/sbom/mod.rs
So far, the concept of product produced by vendor (organization) and having a multiple versions that can be linked to an sbom has been implemented.
All other concepts, like:
* Product hierarchies
* Product version ranges and linking to advisories
* Linking products to identifiers, like cpes, purls or hashes
will be discussed in the future.
> Initial implementation of product concept

- etc/test-data/csaf/rhsa-2024_3666.json
- modules/fundamental/src/advisory/endpoints/test.rs
- modules/ingestor/src/service/advisory/csaf/loader.rs
Fixes #382
I'm pretty sure this was accidentally fixed by #380 but I added a test affirming it.
> Affirm CSAF advisory w/multiple vulnerabilities loads

- Cargo.lock
- common/Cargo.toml
- common/src/db/query.rs
This is prereq for sorting by calculated columns like `average_score`
> Allow filtering and sorting from synthetic non-Entity columns.

- integration-tests/src/sbom/graph/tests.rs
- modules/fundamental/src/advisory/endpoints/test.rs
- modules/fundamental/src/advisory/service/test.rs
- modules/fundamental/src/package/service/test.rs
- modules/fundamental/src/sbom/endpoints/mod.rs
- modules/fundamental/src/sbom/model/mod.rs
> fix: Restore /api/v1/sbom/{key} SBOM metadata access

- modules/fundamental/src/advisory/service/mod.rs
> fix: enable sorting advisories by average_severity

- common/src/db/query.rs
```
foo=null  ---> WHERE "foo" IS NULL
foo!=null ---> WHERE "foo" IS NOT NULL
foo=NuLl  ---> WHERE "foo" IS NULL
```
> feat: support IS [NOT] NULL in queries

- entity/src/sbom.rs
- entity/src/sbom_node.rs
- entity/src/sbom_package.rs
- integration-tests/src/sbom/test/cyclonedx.rs
- integration-tests/src/sbom/test/perf.rs
- integration-tests/src/sbom/test/spdx.rs
- migration/src/m0000250_create_sbom_package.rs
- modules/fundamental/README.md
- modules/fundamental/src/sbom/endpoints/mod.rs
- modules/fundamental/src/sbom/model/mod.rs
- modules/fundamental/src/sbom/service/sbom.rs
- modules/graphql/src/endpoints.rs
- modules/ingestor/README.md
- modules/ingestor/src/graph/sbom/common.rs
- modules/ingestor/src/graph/sbom/cyclonedx.rs
- modules/ingestor/src/graph/sbom/mod.rs
- modules/ingestor/src/graph/sbom/spdx.rs
Closes #413 
---
This builds on ~~#423~~ and #419 and should only be merged after those.
> feat: search SBOMs by PURL or package id

- modules/fundamental/src/sbom/endpoints/mod.rs
- modules/fundamental/src/sbom/service/sbom.rs
> feat: add filtering/query to "find by sbom package"

- server/src/lib.rs
> fix: appease graphql and openapi paths wrt slashes

- entity/src/advisory_vulnerability.rs
- entity/src/vulnerability.rs
- migration/src/lib.rs
- migration/src/m0000370_add_cwe.rs
- modules/fundamental/src/advisory/model/details/advisory_vulnerability.rs
- modules/fundamental/src/package/model/details/package_version.rs
- modules/fundamental/src/package/model/details/qualified_package.rs
- modules/fundamental/src/vulnerability/endpoints/test.rs
- modules/fundamental/src/vulnerability/model/details/mod.rs
- modules/fundamental/src/vulnerability/model/mod.rs
- modules/fundamental/src/vulnerability/model/summary.rs
- modules/graphql/src/vulnerability.rs
- modules/ingestor/src/graph/advisory/mod.rs
- modules/ingestor/src/graph/vulnerability/mod.rs
- modules/ingestor/src/service/advisory/csaf/loader.rs
- modules/ingestor/src/service/advisory/osv/loader.rs
- modules/ingestor/src/service/cve/loader.rs
Closes #281 
Should be merged after #442, #452 , #451.
> feat: add CWE for vulnerabilities

- common/src/db/query.rs
- modules/fundamental/src/sbom/service/sbom.rs
> fix: the q param now works for /api/v1/sbom/{key}/packages

- entity/src/labels.rs
- modules/fundamental/src/advisory/endpoints/label.rs
- modules/fundamental/src/advisory/endpoints/mod.rs
- modules/fundamental/src/advisory/endpoints/test.rs
- modules/fundamental/src/sbom/endpoints/label.rs
- modules/fundamental/src/sbom/endpoints/mod.rs
- modules/ingestor/src/service/mod.rs
This PR:
* Adds support for settings labels during the upload
* Fixes a few issues around labels in the OpenAPI spec
Closes #483
> Improve labels

- modules/fundamental/src/purl/model/details/purl.rs
- modules/fundamental/src/vulnerability/service/mod.rs
> Apply distinct to query for vulnerabilities.

- modules/fundamental/src/product/endpoints/mod.rs
- modules/fundamental/src/product/model/mod.rs
- modules/fundamental/src/product/model/summary.rs
- modules/fundamental/src/product/service/mod.rs
This PR adds more data to product API, such as vendor and versions for the product
> feat: add more data to the products API

- modules/fundamental/src/organization/endpoints/mod.rs
> fix: swagger-ui docs for organization

- modules/fundamental/src/product/endpoints/mod.rs
- modules/fundamental/src/product/model/details.rs
> fix: swagger-ui for product details

- modules/ui/Cargo.toml
- modules/ui/src/lib.rs
- server/Cargo.toml
- server/src/lib.rs
- trustd/Cargo.toml
> fix: remove "ui" feature

- entity/Cargo.toml
Enabling derive as suggested here https://github.com/trustification/trustify/pull/557#issuecomment-2236364038
> fix: strum build error

- modules/fundamental/src/advisory/endpoints/label.rs
- modules/fundamental/src/advisory/endpoints/mod.rs
- modules/fundamental/src/organization/endpoints/mod.rs
- modules/fundamental/src/product/endpoints/mod.rs
- modules/fundamental/src/purl/endpoints/base.rs
- modules/fundamental/src/purl/endpoints/mod.rs
- modules/fundamental/src/purl/endpoints/type.rs
- modules/fundamental/src/purl/endpoints/version.rs
- modules/fundamental/src/sbom/endpoints/label.rs
- modules/fundamental/src/sbom/endpoints/mod.rs
- modules/fundamental/src/vulnerability/endpoints/mod.rs
- modules/importer/src/endpoints.rs
Fixes some of the errors in #580
> fix: Add openapi operation ids

- migration/src/lib.rs
- migration/src/m0000470_cascade_sbom_delete.rs
- modules/fundamental/src/sbom/endpoints/mod.rs
- modules/fundamental/src/sbom/endpoints/test.rs
- modules/fundamental/src/sbom/service/sbom.rs
> feat: Add api to delete sboms

- modules/fundamental/src/error.rs
> Only log internal server errors, don’t send details to the API user.

- modules/fundamental/src/error.rs
- modules/fundamental/src/product/endpoints/mod.rs
- modules/fundamental/src/product/endpoints/test.rs
- modules/fundamental/src/product/service/mod.rs
- modules/fundamental/src/product/service/test.rs
- modules/fundamental/src/sbom/endpoints/mod.rs
> feat: Add api to delete products

- modules/importer/src/model/osv.rs
- modules/importer/src/server/common/walker/git.rs
- modules/importer/src/server/osv/mod.rs
- modules/importer/src/server/osv/walker.rs
- server/src/sample_data.rs
Also, add RustSec as a pre-configured, disabled option.
Closes #587
> feat: add the ability to specify a branch for importing OSV

- migration/src/lib.rs
- migration/src/m0000490_cascade_advisory_delete.rs
- modules/fundamental/src/advisory/endpoints/mod.rs
- modules/fundamental/src/advisory/endpoints/test.rs
- modules/fundamental/src/advisory/service/mod.rs
- modules/fundamental/src/advisory/service/test.rs
> feat: Add api to delete Advisories.

- modules/fundamental/src/vulnerability/endpoints/mod.rs
- modules/fundamental/src/vulnerability/endpoints/test.rs
- modules/fundamental/src/vulnerability/service/mod.rs
- modules/fundamental/src/vulnerability/service/test.rs
> feat: Add api to delete Vulnerabilities.

- migration/src/lib.rs
- migration/src/m0000501_perf_indexes.rs
First batch of indexes identified via loadtesting. There will be more.
When these are applied via migration it is always useful to run:
```sql
VACUUM ANALYZE;
REINDEX database;
```
> Add some perf indexes

- common/infrastructure/src/app/http.rs
- common/infrastructure/src/health/mod.rs
- common/src/db/limiter.rs
- modules/fundamental/src/endpoints.rs
- modules/graphql/src/endpoints.rs
- modules/ingestor/src/graph/advisory/advisory_vulnerability.rs
I found via ` cargo clippy -- -W clippy::redundant_clone`
> chore: removes redundant clones

- modules/fundamental/src/vulnerability/service/mod.rs
- modules/fundamental/src/vulnerability/service/test.rs
> Add test for various vulnerability queries

- common/src/config.rs
- common/src/db/mod.rs
- test-context/src/lib.rs
The default pg max conns is still 100 - there are plans to bump this in pg at some point though that day is not now, dialing back until then.
> better out of the box generic db conn settings

- Cargo.lock
- Cargo.toml
- common/src/config.rs
- modules/ingestor/src/service/mod.rs
- modules/storage/Cargo.toml
- modules/storage/src/service/dispatch.rs
- modules/storage/src/service/fs.rs
- modules/storage/src/service/mod.rs
- modules/storage/src/service/s3.rs
- server/src/lib.rs
> feat: S3 storage backend

- common/src/config.rs
> minor tweak to max min conn env vars

- Cargo.lock
- common/src/config.rs
- modules/storage/Cargo.toml
- modules/storage/src/service/s3.rs
- server/src/lib.rs
> fix: make storage CLI options mutually exclusive

- Cargo.lock
- Cargo.toml
- common/src/db/query.rs
- migration/src/m0000030_create_sbom.rs
Following their release plan on taking it one step at a time
* https://www.sea-ql.org/blog/2024-08-04-sea-orm-1.0/#release-planning
> chore: updating sea-orm

- .github/workflows/ci.yaml
- openapi.yaml
- xtask/src/openapi.rs
This will allow use to more easily spot and review API changes.
> chore: check in generated openapi spec.

- migration/src/lib.rs
- migration/src/m0000520_scale_indexes.rs
Mitigates issue with perf on api/v1/vulnerability (at scale). 
Fixes #645.
> chore - add indexes to assist sorting at scale 

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/infrastructure/Cargo.toml
- common/infrastructure/src/app/http.rs
- common/src/model.rs
- common/src/model/bytesize.rs
- modules/importer/Cargo.toml
- modules/importer/src/endpoints.rs
- modules/importer/src/model/csaf.rs
- modules/importer/src/model/sbom.rs
- modules/importer/src/server/csaf/mod.rs
- modules/importer/src/server/sbom/mod.rs
- modules/importer/src/server/sbom/storage.rs
- modules/importer/src/test.rs
- openapi.yaml
- server/src/sample_data.rs
- xtask/schema/generate-dump.json
- xtask/src/dataset.rs
- xtask/src/openapi.rs
- xtask/src/schema.rs
Also, switch the UI from tag to branch
> feat: allow setting a size limit when importing SBOMs

- modules/fundamental/src/purl/service/mod.rs
- modules/fundamental/src/purl/service/test.rs
This commit also adds a basic test.
Closes #676
> fix: PurlService - purl_by_purl bug

- modules/fundamental/src/product/endpoints/mod.rs
- modules/fundamental/src/product/model/details.rs
- modules/fundamental/src/vulnerability/endpoints/mod.rs
- modules/fundamental/src/vulnerability/model/details/vulnerability_advisory.rs
- openapi.yaml
Same problem was happening with the product sbom head type.
> Fix: the vulnerability sbom status was not showing up in the openapi spec.

- docs/env-vars.md
has relation with https://github.com/trustification/trustify/issues/689 and https://github.com/trustification/trustify/issues/671
> docs: adds a list of env-vars

- modules/importer/src/endpoints.rs
- openapi.yaml
* if-match header is no longer required
* rename getImporterReports to listImporter reports
> fix: importer openapi definitions

- modules/ingestor/src/service/format.rs
Inspired by #706
Thanks @helio-frota
> Remove Read buffer allocations

- docs/env-vars.md
> docs: add docs for OIDC variables

- .github/workflows/build-binary.yaml
- .github/workflows/container-latest.yaml
> build: build a "latest" container from main

- .cargo/config.toml
- .gitignore
- modules/importer/src/runner/clearly_defined/walker.rs
- modules/importer/src/runner/common/walker/git.rs
- modules/importer/src/runner/cve/walker.rs
- modules/importer/src/runner/osv/walker.rs
- test-context/src/lib.rs
Reduces clone time for CVE importer from ~30m down to ~1m
> feat: speed up initial clones of git repos

- Cargo.lock
- modules/importer/Cargo.toml
- modules/importer/src/endpoints.rs
- modules/importer/src/model/clearly_defined.rs
- modules/importer/src/model/cwe.rs
- modules/importer/src/model/mod.rs
- modules/importer/src/runner/clearly_defined/mod.rs
- modules/importer/src/runner/clearly_defined/walker.rs
- modules/importer/src/runner/common/mod.rs
- modules/importer/src/runner/common/walker/git.rs
- modules/importer/src/runner/common/walker/mod.rs
- modules/importer/src/runner/cve/walker.rs
- modules/importer/src/runner/cwe/mod.rs
- modules/importer/src/runner/cwe/walker.rs
- modules/importer/src/runner/mod.rs
- modules/importer/src/runner/osv/walker.rs
- openapi.yaml
- server/src/sample_data.rs
- xtask/schema/generate-dump.json
Clean up some typos.
Regenerate OpenAPI.
> Add CWE Catalog importer, daily interval.

- .github/scripts/dev-build.sh
* https://github.com/trustification/trustify/issues/725#issuecomment-2320209288
> chore: basic script based on ctron's step by step

- server/src/lib.rs
> Allow disabling the GraphQL endpoint, and do so by default, fix mime type

- etc/test-data/cve/CVE-2024-26308.json
- modules/ingestor/src/service/advisory/cve/divination.rs
- modules/ingestor/src/service/advisory/cve/loader.rs
- modules/ingestor/src/service/advisory/cve/mod.rs
> Apply heuristics to divine pURLs from CVERecords iff possible.

- Cargo.lock
- common/Cargo.toml
- migration/Cargo.toml
- modules/fundamental/Cargo.toml
- modules/graphql/Cargo.toml
- modules/importer/Cargo.toml
- modules/ingestor/Cargo.toml
- modules/storage/Cargo.toml
- server/Cargo.toml
- test-context/Cargo.toml
- trustd/Cargo.toml
Based on `RUSTFLAGS=-Wunused-crate-dependencies cargo build`
> chore: removes unused deps

- modules/importer/src/runner/common/walker/git.rs
Resolves #775
I finally figured out how to update the shallow clone, setting the fetch depth to `i32::MAX` to signal infinite fetch depth, per https://git-scm.com/docs/shallow
I had wrongly assumed depth=0 signaled infinite depth -- it does for an initial clone, but not an update of a shallow one.
Essentially, this improves the "day 0" experience -- the first walk of the shallow clone takes no more than a few minutes. But the annoying ~30 minute fetch is deferred to the first update of the shallow clone, effectively turning it into a deep clone, after which subsequent fetches are fast.
I think that's a workable compromise until libgit2's perf issue is addressed.
> Restore the shallow clone behavior of the git walkers

- modules/analysis/src/service.rs
> silence the analysis graph noise

- modules/fundamental/src/advisory/model/mod.rs
- modules/fundamental/src/license/model/mod.rs
- modules/fundamental/src/product/model/mod.rs
- modules/fundamental/src/sbom/model/mod.rs
- openapi.yaml
Closes https://github.com/trustification/trustify/issues/792
> fixes: openapi: uuid types don't look like uuids #792

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/decompress.rs
- common/src/lib.rs
- modules/fundamental/Cargo.toml
- modules/fundamental/src/advisory/endpoints/mod.rs
- modules/fundamental/src/error.rs
- modules/fundamental/src/sbom/endpoints/mod.rs
- test-context/src/lib.rs
Also, drop unnecessary error enum and Sync/Send traits.
> feat: support compressed upload

- modules/fundamental/src/purl/service/test.rs
- modules/fundamental/src/sbom/endpoints/mod.rs
- modules/fundamental/src/sbom/endpoints/test.rs
- modules/fundamental/src/sbom/model/details.rs
- modules/fundamental/src/sbom/service/sbom.rs
- modules/fundamental/src/sbom/service/test.rs
- modules/fundamental/tests/sbom/reingest.rs
- modules/graphql/src/sbomstatus.rs
- openapi.yaml
cc @carlosthe19916 This might have an impact on the UI. At least a positive one, as some calls are faster. Not sure if the UI needs to be adapted.
Closes: https://github.com/trustification/trustify/issues/800
> chore: reduce the amount of data

- etc/test-data/spdx/issue-552.json
- modules/fundamental/tests/sbom/spdx.rs
- modules/fundamental/tests/sbom/spdx/issue_552.rs
- modules/ingestor/src/graph/sbom/common/relationship.rs
- modules/ingestor/src/graph/sbom/spdx.rs
> fix: handle NONE and NOASSERTION as relationship targets

- Cargo.lock
- xtask/Cargo.toml
- xtask/src/dataset.rs
- xtask/src/main.rs
Closes: https://github.com/trustification/trustify/issues/849
> fix: init logger only once, use tracing setup

- .github/workflows/rita-new-pr.yaml
- .github/workflows/rita-pr-merged.yaml
> apparently, context vars must be used in steps, next to runners

- modules/fundamental/src/sbom/endpoints/mod.rs
- openapi.yaml
> fix: update openapi spec

- Cargo.lock
- Cargo.toml
- modules/fundamental/src/ai/service/mod.rs
- modules/fundamental/src/ai/service/test.rs
- modules/fundamental/src/ai/service/tools.rs
use patched langchain to fix bug.
Langchain was adding extra user message “2” to the message history.
> [ai]: support sending multiple new user messages

- modules/fundamental/src/ai/endpoints/mod.rs
- modules/fundamental/src/ai/endpoints/test.rs
- modules/fundamental/src/ai/model/mod.rs
- modules/fundamental/src/ai/service/mod.rs
- modules/fundamental/src/ai/service/test.rs
- openapi.yaml
* /api/v1/ai/flags - can be used to determine if completions endpoint is enabled.
* /api/v1/ai/tools - can be used to get a list of tools and the descriptions needs to integrate them with an LLM.
* /api/v1/ai/tools/{name} - calls the named tool.
> Add more AI related endpoints.

- modules/fundamental/tests/advisory/csaf/reingest.rs
- modules/ingestor/src/service/advisory/csaf/creator.rs
> fix: don't clear qualifiers when ingesting CSAF

- modules/ingestor/src/service/dataset/mod.rs
We now ignore .DS_Store entries.
> fix: test failure due to .DS_Store files being present

- modules/fundamental/src/sbom/endpoints/mod.rs
- modules/fundamental/src/sbom/service/sbom.rs
- modules/fundamental/src/sbom/service/test.rs
- openapi.yaml
Closes https://github.com/trustification/trustify/issues/889
> feat: add an endpoint to get the counts of sboms per purl

- modules/fundamental/tests/advisory/osv/reingest.rs
Follow up to #901, amending the existing test
> test: add qualified purl assertion to the osv test

- Cargo.lock
- Cargo.toml
- common/src/lib.rs
- common/src/serde.rs
- modules/importer/src/model/csaf.rs
- modules/importer/src/model/sbom.rs
- modules/importer/src/runner/csaf/mod.rs
- modules/importer/src/runner/csaf/report.rs
- modules/importer/src/runner/csaf/storage.rs
- modules/importer/src/runner/sbom/mod.rs
- modules/importer/src/runner/sbom/report.rs
- modules/importer/src/runner/sbom/storage.rs
- modules/importer/src/test.rs
- openapi.yaml
- server/src/sample_data.rs
- xtask/schema/generate-dump.json
- xtask/src/dataset.rs
This allows working around [SECDATA-723](https://issues.redhat.com/browse/SECDATA-723)
> feat: allow ignoring missing (404) files when importing

- docs/env-vars.md
> chore: docs missing env vars

- common/src/db/query.rs
- common/src/db/query/columns.rs
- common/src/db/query/filtering.rs
Also added a Display impl for Columns to assist in debugging.
> Refactor sea_orm-dependent logic out of query and into filtering

- modules/importer/src/model/mod.rs
- modules/importer/src/runner/report.rs
- openapi.yaml
Closes https://github.com/trustification/trustify/issues/960
> chore: define model of import report

- modules/fundamental/src/sbom/model/mod.rs
- openapi.yaml
Closes https://github.com/trustification/trustify/issues/975
cc @kahboom
> fix: add missing "number of packages" field

- entity/src/advisory_vulnerability.rs
- modules/fundamental/src/vulnerability/model/details/vulnerability_advisory.rs
- openapi.yaml
Closes https://github.com/trustification/trustify/issues/976
cc @kahboom
> fix: add missing "number_of_vulnerabilities" field

- migration/src/lib.rs
- migration/src/m0000720_alter_sbom_fix_null_array.rs
Closes https://github.com/trustification/trustify/issues/984
> fix: have a default empty array

- modules/fundamental/src/advisory/endpoints/test.rs
> test: adds a test for multiple csaf file upload

- .github/workflows/ci.yaml
- .github/workflows/docs.yaml
- docs/book/.gitignore
- docs/book/Makefile
- docs/book/antora-playbook.yaml
- docs/book/antora.yml
- docs/book/modules/ROOT/nav.adoc
- docs/book/modules/ROOT/pages/index.adoc
- docs/book/modules/admin/nav.adoc
- docs/book/modules/admin/pages/index.adoc
- docs/book/package-lock.json
- docs/book/package.json
This PR add initial docs support based on asciidoc. It should publish to the repositories homepage.
> Add docs based on asciidoc

- modules/fundamental/src/purl/model/details/purl.rs
- modules/fundamental/src/vulnerability/service/test.rs
> feat: correlate vulnerabilties for purls using product statuses

- Cargo.lock
- modules/fundamental/Cargo.toml
- modules/fundamental/src/ai/endpoints/mod.rs
- modules/fundamental/src/ai/endpoints/test.rs
- modules/fundamental/src/ai/service/mod.rs
- modules/fundamental/src/ai/service/tools/mod.rs
- modules/fundamental/src/ai/service/tools/remote.rs
To have the agent invoke the local tools via remote http calls, add the following env vars:
AGENT_DISABLE_LOCAL_TOOLS=true
REMOTE_AI_TOOL_URLS=http://localhost:8080/api/v1/ai/tools
> feat[ai]: agent can now use remote tools.

- docs/book/modules/admin/examples/.gitignore
- docs/book/modules/admin/examples/trustify/database.tf
- docs/book/modules/admin/examples/trustify/main.tf
- docs/book/modules/admin/examples/trustify/sso.tf
- docs/book/modules/admin/examples/trustify/storage.tf
- docs/book/modules/admin/nav.adoc
- docs/book/modules/admin/pages/infrastructure.adoc
This is a PR, providing some example scripts as part of the documentation for setting up AWS managed resources required for a trustify installation.
> Add terrform example scripts

- docs/book/package-lock.json
- docs/book/package.json
- docs/docs.trustification.dev/010-ImageStream.yaml
- docs/docs.trustification.dev/020-BuildConfig.yaml
- docs/docs.trustification.dev/030-Deployment.yaml
- docs/docs.trustification.dev/040-Service.yaml
- docs/docs.trustification.dev/050-Ingress.yaml
- docs/docs.trustification.dev/README.md
> chore: add a kubernetes deployment for hosting the docs

- .github/workflows/build-binary.yaml
- modules/fundamental/src/sbom/service/sbom.rs
- modules/importer/schema/importer.json
- xtask/src/schema.rs
> ci: generate importer schema

- etc/test-data/csaf/CVE-2024-34500.json
- etc/test-data/csaf/CVE-2024-34502.json
- etc/test-data/csaf/CVE-2024-34506.json
- etc/test-data/csaf/CVE-2024-34507.json
This is related to https://github.com/trustification/trustify/issues/1036#issue-2680107467
to make easy for us to select those files when testing upload.
> chore: Adds 4 extra files for tests

- common/src/db/query/filter.rs
- modules/fundamental/src/advisory/endpoints/test.rs
- modules/fundamental/src/advisory/service/mod.rs
- modules/fundamental/src/sbom/endpoints/test.rs
> fix: ensure sbom's and adv's can be filtered/sorted by ingested date

- migration/src/m0000720_alter_sbom_fix_null_array.rs
Closes: https://github.com/trustification/trustify/issues/1089
> fix: actually set a default value, instead of `null`

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- openapi.yaml
What's different this time is that we have an actual release and a release branch.
> chore: prepare release 0.1.0

- entity/src/conversation.rs
- entity/src/lib.rs
- migration/src/lib.rs
- migration/src/m0000820_create_conversation.rs
- modules/fundamental/src/ai/service/mod.rs
- modules/fundamental/src/ai/service/test.rs
> feat[ai]: Add crud operations for a conversations table

- etc/test-data/cyclonedx/66FF73123BB3489.json
- modules/analysis/src/endpoints.rs
- modules/ingestor/src/graph/purl/package_version.rs
- modules/ingestor/src/graph/sbom/cyclonedx.rs
Fixes #1147
Only analysis endpoints affected, no change to /api/v2/purl endpoint.
> feat: create VariantOf relationship from cdx pedigree/variants

- modules/analysis/src/endpoints/test.rs
See https://issues.redhat.com/browse/TC-2053
This doesn't include relationships in the response of /api/v2/purl as there's a pending request to remove that requirement.
> Add unit test affirming TC-2053

- migration/src/lib.rs
- migration/src/m0000840_add_relationship_14_15.rs
- modules/analysis/src/endpoints/test.rs
- modules/ingestor/src/graph/sbom/spdx.rs
Part of issue #1140
The relationships table did not have records for #14 DescribedBy and #15 PackageOf
> Add support for spdx "relationshipType": "PACKAGE_OF"

- etc/test-data/spdx/1178.json
- modules/analysis/src/endpoints/test.rs
> Affirm AncestorOf relationship for SPDX files

- common/infrastructure/Cargo.toml
- common/infrastructure/src/tracing.rs
- docs/design/log_tracing.md
- etc/dev-traces/compose.yaml
- etc/dev-traces/config.yaml
* Adds a compose with Jaeger and OTELCOL
* Fixes a problem with actix-web tracing
> feat: Seeing OTEL traces at development time

- etc/test-data/cyclonedx/pypi_aiohttp.json
- etc/test-data/osv/GHSA-45c4-8wx5-qw6w.json
- migration/src/lib.rs
- migration/src/m0000850_python_version.rs
- migration/src/m0000850_python_version/python_version_matches.sql
- migration/src/m0000850_python_version/pythonver_cmp.sql
- migration/src/m0000850_python_version/version_matches.sql
- modules/fundamental/tests/sbom/details.rs
- modules/fundamental/tests/sbom/mod.rs
- modules/ingestor/src/service/advisory/osv/loader.rs
- modules/ingestor/src/service/advisory/osv/translate.rs
- modules/ingestor/tests/version/mod.rs
- modules/ingestor/tests/version/pythonver.rs
https://issues.redhat.com/browse/TC-2174
Backport:
- https://github.com/trustification/trustify/pull/1212
> [release/0.2.z] TC-2174 OSV Python ecosystem management 

- etc/test-data/cyclonedx/ghsa_test.json
- etc/test-data/osv/GHSA-c25x-cm9x-qqgx.json
- modules/fundamental/tests/sbom/details.rs
https://issues.redhat.com/browse/TC-2216
Add a test to cover the GHSA OSV crates.io correlation use case.
> TC-2216 OSV crates.io: add test

- etc/test-data/cyclonedx/ghsa_test.json
- etc/test-data/osv/GHSA-c25x-cm9x-qqgx.json
- modules/fundamental/tests/sbom/details.rs
https://issues.redhat.com/browse/TC-2216
Backport:
- https://github.com/trustification/trustify/pull/1226
> [release/0.2.z] TC-2216 OSV crates.io: add test

- modules/analysis/src/endpoints/test.rs
added ignored test for when #1232 is worked out.
> relationship filtering test for #1232

- entity/src/version_scheme.rs
- etc/test-data/cyclonedx/ghsa_test.json
- etc/test-data/osv/GHSA-4h4p-553m-46qh.json
- modules/fundamental/tests/sbom/details.rs
- modules/ingestor/src/service/advisory/osv/loader.rs
- modules/ingestor/src/service/advisory/osv/translate.rs
https://issues.redhat.com/browse/TC-2222
> TC-2222 OSV GHSA - Ecosystem Golang

- entity/src/version_scheme.rs
- etc/test-data/cyclonedx/ghsa_test.json
- etc/test-data/osv/GHSA-4h4p-553m-46qh.json
- modules/fundamental/tests/sbom/details.rs
- modules/ingestor/src/service/advisory/osv/loader.rs
- modules/ingestor/src/service/advisory/osv/translate.rs
https://issues.redhat.com/browse/TC-2222
Backport:
- #1243
> [release/0.2.z] TC-2222 OSV GHSA - Ecosystem Golang

- entity/src/sbom_external_node.rs
- migration/src/lib.rs
- migration/src/m0000890_create_sbom_external_node.rs
Implement sbom_external_node entity as defined in https://github.com/trustification/trustify/blob/adr-external-references/docs/adrs/00003-external-references.md
> Implement sbom_external_node entity (ADR 00003-external-references)

- entity/src/version_scheme.rs
- etc/test-data/cyclonedx/ghsa_test.json
- etc/test-data/osv/GHSA-2ccf-ffrj-m4qw.json
- modules/fundamental/tests/sbom/details.rs
- modules/ingestor/src/service/advisory/osv/loader.rs
- modules/ingestor/src/service/advisory/osv/translate.rs
https://issues.redhat.com/browse/TC-2223
> TC-2223 OSV GHSA - Ecosystem npm

- common/infrastructure/src/otel.rs
Related to #1255 
Related to #335
> chore: Remove actix_web_prom from RUST_LOG

- entity/src/version_scheme.rs
- etc/test-data/cyclonedx/ghsa_test.json
- etc/test-data/osv/GHSA-3cqw-pxgr-jhrm.json
- migration/src/lib.rs
- migration/src/m0000910_insert_packagist_version_scheme.rs
- migration/src/m0000910_insert_packagist_version_scheme/version_matches.sql
- modules/fundamental/tests/sbom/details.rs
- modules/ingestor/src/service/advisory/osv/loader.rs
- modules/ingestor/src/service/advisory/osv/translate.rs
https://issues.redhat.com/browse/TC-2224
> TC-2224 OSV GHSA - Ecosystem Packagist (PHP)

- .github/workflows/openapi.yaml
Relates to https://github.com/trustification/trustify-ui/pull/331
> OpenAPI generated files are not committed to UI repository

- entity/src/version_scheme.rs
- etc/test-data/cyclonedx/ghsa_test.json
- etc/test-data/osv/GHSA-rh58-r7jh-xhx3.json
- modules/fundamental/tests/sbom/details.rs
- modules/ingestor/src/service/advisory/osv/loader.rs
- modules/ingestor/src/service/advisory/osv/translate.rs
https://issues.redhat.com/browse/TC-2239
> TC-2239 OSV GHSA - Ecosystem NuGet (Microsoft)

- Cargo.toml
- common/src/db/embedded.rs
- etc/deploy/compose/compose.yaml
- trustd/src/db.rs
Related to https://github.com/trustification/trustify/issues/1275
> feat: Upgrade postgresql to 17

- .github/workflows/latest-release.yaml
Closes: https://github.com/trustification/trustify/issues/1288
> ci: also publish latest release branch containers

- migration/src/lib.rs
- migration/src/m0000960_sort_indexes_qualified_purl.rs
dropped all gist indexes and added specific indexes for sorting qualified_purl
> perf: add sort indexes for qualified_purl

- etc/test-data/cyclonedx/simple-ext-a.json
- etc/test-data/cyclonedx/simple-ext-b.json
- modules/fundamental/tests/sbom/cyclonedx/external.rs
- modules/fundamental/tests/sbom/cyclonedx/mod.rs
- modules/ingestor/src/graph/sbom/cyclonedx.rs
- modules/ingestor/src/graph/sbom/mod.rs
* removed some [duplicate code](https://github.com/trustification/trustify/pull/1303/commits/cfac19a2bbf97ee54cc44aca9b308f67e04a2bab)
* added [simple cdx](https://github.com/trustification/trustify/pull/1303/commits/432a6803475ec81146a8ff15a624ace6d89a9ebc) along with [naive test](https://github.com/trustification/trustify/pull/1303/commits/6e69c75030a8274838e98770b881e588ab01599c)
> Resolve cdx ext references

- Cargo.lock
- Cargo.toml
It is working https://github.com/trustification/trustify/discussions/1313
> chore: update csaf-walker

- .github/actions/build-container/action.yaml
- .github/scripts/Containerfile.xtask
- .github/workflows/build-binary.yaml
- .github/workflows/ci.yaml
- .github/workflows/latest-release.yaml
- .github/workflows/release.yaml
- Cargo.lock
- Cargo.toml
- modules/fundamental/tests/sbom/details.rs
- modules/ingestor/src/service/format.rs
- modules/ingestor/src/service/sbom/cyclonedx.rs
- openapi.yaml
Just preparing, we're not releasing right now
> chore: prepare release 0.2.6

- e2e/README.md
- e2e/ds3.hurl
This is a first attempt to create end to end tests based on [hurl](https://hurl.dev/) (thanks @helio-frota). 
I really like it so far. It was very easy to create a test that uploads ds3 dataset and do some basic responses for the sbom vulnerability matching.
It can also be very nicely integrated into our CI workflow.
> feat: introduct e2e tests based on hurl

- etc/test-data/cyclonedx/ghsa_test.json
- etc/test-data/osv/GHSA-qq9f-q439-2574.json
- modules/fundamental/tests/sbom/details.rs
https://issues.redhat.com/browse/TC-2165
The issue has been already implemented but I figured out a test, consistently with what has been done for the other GHSA ecosystems, is missing so I've added it.
> TC-2165 OSV GHSA - Ecosystem Maven: add test

- Cargo.lock
- Cargo.toml
- openapi.yaml
Also: Use Rust 2024 edition resolver (3).
> chore: prepare release 0.2.8

- migration/src/m0000010_init_up.sql
- modules/fundamental/tests/sbom/spdx.rs
- modules/fundamental/tests/sbom/spdx/parallel.rs
- modules/ingestor/src/graph/sbom/mod.rs
> fix: don't create duplicate documents when ingesting in parallel (spdx)

- modules/analysis/src/endpoints/tests/rh_variant.rs
- modules/analysis/src/service/collector.rs
- modules/analysis/src/service/load.rs
Ancestor queries should resolve any external sboms that refer to any node.
Fixes: #1393
> fix: ancestor query so that any external parent sboms are returned

- modules/fundamental/tests/advisory/csaf/mod.rs
- modules/fundamental/tests/advisory/csaf/parallel.rs
- modules/fundamental/tests/advisory/cve/mod.rs
- modules/fundamental/tests/advisory/cve/parallel.rs
- modules/fundamental/tests/advisory/osv/mod.rs
- modules/fundamental/tests/advisory/osv/parallel.rs
- modules/fundamental/tests/sbom/cyclonedx/mod.rs
- modules/fundamental/tests/sbom/cyclonedx/parallel.rs
- modules/ingestor/src/graph/advisory/mod.rs
- modules/ingestor/src/graph/mod.rs
- modules/ingestor/src/graph/sbom/mod.rs
This fixes issue #1395 also for advisories and adds a test for CDX. Which was already covered by a previous PR, but didn't have a test.
> Ensure no duplication of documents during parallel upload in more locations

- Cargo.lock
- common/Cargo.toml
- common/src/config.rs
- common/src/db/mod.rs
- trustd/src/db.rs
> fix: prevent database passwords being logged

- etc/test-data/spdx/rh/product_component/openssl-3.0.7-18.el9_2.spdx.json
- modules/analysis/src/endpoints/tests/rh_variant.rs
- modules/analysis/src/service/collector.rs
- modules/analysis/src/service/mod.rs
- modules/analysis/src/service/test.rs
This PR refactors for correct behavior in analysis graph endpoint - there are some areas we can speed up though opted for simplicity to illustrate 'intent'.https://github.com/trustification/trustify/pull/1451.
Note - we can follow up with perf PR
> fix: refactor external sbom

- modules/fundamental/src/ai/service/tools/package_info.rs
- modules/fundamental/src/error.rs
- modules/fundamental/src/purl/endpoints/mod.rs
- modules/fundamental/src/purl/endpoints/test.rs
- modules/fundamental/src/purl/model/details/purl.rs
- modules/fundamental/src/purl/service/mod.rs
- modules/fundamental/src/purl/service/test.rs
- modules/fundamental/src/vulnerability/service/test.rs
- modules/fundamental/tests/advisory/csaf/delete.rs
- modules/fundamental/tests/advisory/csaf/reingest.rs
- modules/fundamental/tests/advisory/osv/reingest.rs
- openapi.yaml
> Revert "feat: add endpoint to process multiple purls"

- modules/fundamental/src/purl/endpoints/base.rs
- modules/fundamental/src/purl/endpoints/mod.rs
- modules/fundamental/src/purl/endpoints/test.rs
- openapi.yaml
fixes #1470
This partially reverts commit 45b228e5ad615eb0ebb83ad8252a7c82a377d82b
> restore base purl endpoints

- migration/src/lib.rs
- migration/src/m0000080_get_purl_refactor.rs
This PR is next mini step in just using the qualified_purl table to resolve purls - note get_purl is not used in many places and may go away eventually.
> chore: incremental refactor of get_purl

- Cargo.lock
- Cargo.toml
- modules/fundamental/Cargo.toml
- modules/fundamental/src/purl/model/details/purl.rs
- modules/fundamental/src/sbom/model/details.rs
- modules/fundamental/tests/advisory/csaf/delete.rs
- modules/fundamental/tests/advisory/csaf/reingest.rs
- modules/fundamental/tests/advisory/osv/reingest.rs
- openapi.yaml
Also, add instrumentation.
Closes: #1473
I was working on this file anyway.
> feat: add score to response

- modules/fundamental/benches/bench-otel.rs
- modules/fundamental/benches/bench.rs
- modules/fundamental/benches/common.rs
> refactor: common code for criterion benches

- e2e/ds3.hurl
- modules/fundamental/src/purl/model/details/purl.rs
fixes: https://github.com/trustification/trustify-ui/issues/402
> fix: add vulnerability details in purl details for product statuses

- modules/fundamental/src/sbom/endpoints/test.rs
- modules/fundamental/src/sbom/service/sbom.rs
> fix: /sbom/by-package api can now sort results by name

- README.md
Mention related upstream projects in `README.md`.
> docs: Mention related projects

- docs/oidc.md
- server/src/profile/api.rs
> fix: allow setting devmode with container keycloak

- etc/test-data/cyclonedx/ghsa_test.json
- etc/test-data/osv/GHSA-458h-wv48-fq75.json
- modules/fundamental/tests/sbom/details.rs
- modules/ingestor/src/service/advisory/osv/loader.rs
https://issues.redhat.com/browse/TC-2388
OSV `last_affected` field from `ranges` events management.
> fix: TC-2388 OSV range with last_affected

- cvss/src/cvss3/mod.rs
- modules/fundamental/src/sbom/endpoints/test.rs
- modules/fundamental/src/vulnerability/service/test.rs
- modules/fundamental/tests/advisory/csaf/delete.rs
- modules/fundamental/tests/advisory/csaf/reingest.rs
- modules/fundamental/tests/sbom/details.rs
- modules/ingestor/src/service/advisory/csaf/loader.rs
> fix: cvss scores with I:N and A:N score properly now

- modules/importer/src/server/mod.rs
> fix: reap crashed jobs so they don't appear "stuck" in the UI

- Cargo.lock
- Cargo.toml
- etc/test-data/csaf/issues/cvss_1/ssa-054046.json
- modules/ingestor/tests/issues.rs
> fix: ensure that an invalid CVSS does not panic

- common/src/db/query.rs
- common/src/db/query/columns.rs
- common/src/db/query/filter.rs
- common/src/db/query/sort.rs
> feat: return a list of valid fields in a query error message

- Cargo.lock
- modules/fundamental/src/advisory/endpoints/test.rs
- modules/fundamental/src/advisory/service/mod.rs
- modules/fundamental/src/sbom/endpoints/mod.rs
- modules/fundamental/src/sbom/endpoints/test.rs
- modules/fundamental/src/sbom/service/sbom.rs
- modules/fundamental/tests/advisory/osv/ingest.rs
- modules/fundamental/tests/sbom/issue_1535.rs
- modules/ingestor/tests/reingest/osv.rs
- openapi.yaml
- test-context/Cargo.toml
- test-context/src/lib.rs
> feat: filter SBOM's and Advisories by labels

- modules/analysis/src/service/load.rs
A few minor optimisations when we load sboms into graph:
* remove unnec ordering
* remove unnec distinct
note- scale-test confirms this a good change.
> perf: minor analysis graph loading optimisation

- modules/analysis/src/service/load.rs
> chore: rollback a minor perf

- common/src/db/query.rs
- openapi.yaml
> reorganize query docs so openapi picks it up

- .github/workflows/scale-test.yaml
Updated the value expected for the `rev` referenced PR accordingly to the dependant PR.
Depends on 
- https://github.com/trustification/trustify-load-test-runs/pull/11
> scale test: update 'rev' PR reference

- RELEASE.md
- docs/adrs/00001-graph-analytics.md
- docs/adrs/00002-analysis-graph.md
- docs/adrs/00003-external-references.md
- docs/book/modules/admin/pages/infrastructure.adoc
- docs/design/log_tracing.md
- modules/analysis/src/service/mod.rs
- modules/fundamental/src/vulnerability/service/test.rs
- modules/fundamental/tests/advisory/csaf/mod.rs
- modules/importer/src/runner/report.rs
- modules/ingestor/src/graph/sbom/common/package.rs
- modules/ingestor/src/service/mod.rs
- modules/ingestor/tests/reingest/osv.rs
typos found via `cargo install typos-cli`
> chore: fix typos

- modules/analysis/src/service/load.rs
- modules/analysis/src/service/mod.rs
> refactor: clean up duplicate code

- common/src/db/query.rs
- common/src/db/query/columns.rs
- common/src/db/query/filtering.rs
- common/src/db/query/sort.rs
- modules/fundamental/src/advisory/service/mod.rs
- modules/fundamental/src/sbom/endpoints/test.rs
- modules/fundamental/src/vulnerability/service/mod.rs
> feat: allow string arrays to be queried in the q= syntax

- common/src/db/query.rs
- common/src/db/query/filter.rs
- openapi.yaml
Turns out it was already supported so we got that feature for free!
> add tests/docs showing how to query for empty strings

- common/src/db/query.rs
- common/src/db/query/columns.rs
- common/src/db/query/filter.rs
- common/src/db/query/filtering.rs
- common/src/db/query/sort.rs
- modules/fundamental/src/advisory/service/mod.rs
- modules/fundamental/src/sbom/endpoints/test.rs
- modules/fundamental/src/vulnerability/service/mod.rs
This reverts commit 4e8589b6099325b35c4be6e998bfce90970068bd.
> Reapply "feat: allow string arrays to be queried in the q= syntax"

- docs/book/README.md
- docs/book/antora-playbook.yaml
- docs/book/antora.yml
- docs/book/modules/migration/nav.adoc
- docs/book/modules/migration/pages/index.adoc
Resolves: TC-2296
Currently contain only one known documented use case from the Jira ticket above but more can come/be added. ~I will left this PR in draft mode and switch it to reviewable state after the reporter of the TC-2296 is satisfied with the result.~
~The part of this PR is also an Antora extension for checking the correctness of API calls (see also added `README.md`).~
> docs: Add v1 to v2 migration guide

- modules/analysis/src/endpoints/tests/mod.rs
We want to know if any future changes break these
> add a few tests matching camp users' input

- modules/importer/src/endpoints.rs
- modules/importer/src/service.rs
- openapi.yaml
> fix: add sorting and pagination to importer report endpoint

- docs/adrs/00007-purl-report.md
Rendered preview: https://github.com/ctron/trustify/blob/feature/adr_da_check_1/docs/adrs/00007-purl-report.md
> docs(adr): Proposal for a "PURL report"

- modules/storage/src/config.rs
- modules/storage/src/service/s3.rs
* feat: allow using path style for S3, #1678
* ensure all config fields are consumed by destructuring.
* feat: Setting compression to None will remove the header, #1682
> S3 backend configuration enhancements

- docs/otel.md
Rendered version: https://github.com/helio-frota/trustify/blob/issue-1648/docs/otel.md
> chore: update otel doc with diagrams

- docs/otel.md
- etc/telemetry/compose.yaml
- etc/telemetry/grafana/dashboards/default.yaml
- etc/telemetry/grafana/dashboards/metrics.json
- etc/telemetry/grafana/dashboards/traces.json
* Also adds skeleton and configs for grafana dashboards
> chore: updates otel dev docs

- modules/fundamental/src/license/service/mod.rs
- modules/fundamental/src/sbom/endpoints/mod.rs
- modules/fundamental/src/sbom/endpoints/test.rs
- openapi.yaml
Fixes: https://github.com/trustification/trustify/issues/1704
> chore: Fix up API definition of /api/v2/sbom/{id}/licenseIds

- Cargo.lock
- entity/Cargo.toml
- entity/src/labels.rs
- modules/fundamental/src/advisory/service/mod.rs
- modules/fundamental/src/error.rs
- modules/fundamental/src/sbom/service/label.rs
- modules/fundamental/src/test/label.rs
- modules/importer/src/service.rs
- modules/ingestor/src/graph/advisory/mod.rs
- modules/ingestor/src/graph/error.rs
- modules/ingestor/src/graph/sbom/mod.rs
This implements label validation, ensuring to eliminate some corner cases up front.
Closes: #1708
> feat: implement validation of labels

- modules/importer/src/model/mod.rs
Add unit tests for Importer methods: is_due, is_running, is_enabled.
Assisted-by: Cursor
> test(importer): increase unit test coverage and refactor test helpers

- .github/workflows/ci.yaml
- .github/workflows/codecov.yaml
CI error:
`= note: /usr/bin/ld: final link failed: No space left on device`
> ci: free more disk space

- common/src/model/bytesize.rs
- modules/analysis/README.md
- modules/analysis/src/endpoints/mod.rs
- modules/analysis/src/model.rs
- modules/analysis/src/service/load.rs
- modules/analysis/src/service/mod.rs
- modules/analysis/src/service/test.rs
- openapi.yaml
Optionall, using details=true, it is now possible to request more details on the internal state of things.
> feat(analysis): provide for status details

- .github/workflows/backport.yaml
- .github/workflows/benchmark.yaml
- .github/workflows/ci.yaml
- .github/workflows/docs.yaml
- .github/workflows/latest-release.yaml
- .github/workflows/openapi.yaml
- .github/workflows/release.yaml
- .github/workflows/rita-new-discussion.yaml
- .github/workflows/rita-new-pr.yaml
- .github/workflows/rita-pr-merged.yaml
- .github/workflows/rita-request-review.yaml
- .github/workflows/scale-test.yaml
Backport:
- https://github.com/trustification/trustify/pull/1783
- https://github.com/trustification/trustify/pull/1794
> ci: using the same ubuntu version across workflows [Backport release/0.3.z]

- modules/fundamental/src/sbom/endpoints/test.rs
fixs: https://github.com/trustification/trustify/issues/1778
> Fix: Avoid errors caused by different orderings of ouput.

- modules/analysis/src/endpoints/tests/latest_filters.rs
- modules/analysis/src/service/load.rs
> chore: missing commit

- docs/book/modules/admin/pages/infrastructure.adoc
Updated documentation for the usage of Red Hat services with 
- Red Hat SSO operator
- Red Hat ODF operator
> Documentation for RHSSO and RHODF

- common/src/db/limiter.rs
- modules/fundamental/src/advisory/model/details/advisory_vulnerability.rs
- modules/fundamental/src/advisory/model/mod.rs
- modules/fundamental/src/advisory/model/summary.rs
- modules/fundamental/src/advisory/service/mod.rs
- modules/fundamental/src/vulnerability/model/mod.rs
Right now we don't have much information:
> chore: more instrumentation when fetching advisories
