backend/api/Cargo.toml

When using the `trustify-cli` command and enabling `RUST_LOG` we get unreadable `sqlx` debug logs:
```console
INFO  sqlx::query] summary="SELECT \"package\".\"id\", \"package\".\"type\", \"package\".\"namespace\", …" db.statement="\n\nSELECT\n  \"package\".\"id\",\n  \"package\".\"type\",\n  \"package\".\"namespace\",\n  \"package\".\"name\"\nFROM\n  \"package\"\nWHERE\n  \"package\".\"type\" = $1\n  AND \"package\".\"namespace\" = $2\n  AND \"package\".\"name\" = $3\nLIMIT\n
```
With this change we can see:
```console
DEBUG sea_orm::driver::sqlx_postgres] SELECT "package"."id", "package"."type", "package"."namespace", "package"."name" FROM "package" WHERE "package"."type" = 'maven' AND "package"."namespace" = 'com.fasterxml.jackson.dataformat' AND "package"."name" = …
```

chore: enable readable debug log

---

.github/workflows/frontend.yml

As mentioned in #19 I find it pretty hard to work with PRs because of those unrelated warnings, which show up on every PR. Even though no changes have been made on those files.
My proposal here is to either merge this PR and disable this step for now, until we find some time to fix those warnigns. Or find a switch for "warnings as errors" and fail the build in the case of violations.
Spamming PRs and not using the outcome to improve the code seems counterproductive.

ci: disable npm lint, as we don't make use of its results right now

---

.github/labeler.yaml
.github/workflows/backend.yaml
.github/workflows/frontend.yml
.github/workflows/labeler.yml

Not sure if you guys consider this PR adds any value or just add lines of code for a problem that might not exist. Feel free to not merge the PR or require changes 
- Add `ci`, `frontend`, or `backend` labels to each PR depending on the directories touched by the PR. Just to add some classification of PRs
- Execute backend/frontend unit tests only when the appropriate directory was touched.
- If a file in the backend folder has been touched, there is no reason to execute the UI tests. It only slows down the total execution time of the set of GH actions.

Automate labeling and CI conditional execution

---

.github/workflows/backend.yaml
graph/Cargo.toml
graph/src/graph/mod.rs

Investigating the failure in https://github.com/trustification/trustify/actions/runs/8234967143/job/22517985508?pr=40#step:9:33, it turned out it was related to multi tests concurrently extracting PostgreSQL to the same folder.
Installing tests to extract PostgreSQL in folder within the system temporary directory enables tests to be executed concurrently.
The drawback with this implementation is that `into_path` consumes `TempDir` hence it won't be automatically deleted at the end of the test but considering the installation directory is within the system temporary directory, I think this could be considered acceptable in the context of tests execution.

PostgreSQL embedded: tests use system temp dir for installation

---

common/Cargo.toml

Build works fine from root, but fails from beneath `graph` and `common` workspaces without enabling the `native-tls` feature for `reqwest` crate.

Enable feature to fix build within child workspace

---

graph/src/db.rs
graph/src/graph/advisory/affected_package_version_range.rs
graph/src/graph/advisory/csaf/mod.rs
graph/src/graph/advisory/fixed_package_version.rs
graph/src/graph/advisory/mod.rs
graph/src/graph/advisory/not_affected_package_version.rs
graph/src/graph/mod.rs
graph/src/graph/package/mod.rs
graph/src/graph/package/package_version.rs
graph/src/graph/package/qualified_package.rs
graph/src/graph/sbom/mod.rs
graph/src/graph/sbom/spdx.rs
graph/src/graph/vulnerability.rs
graph/src/lib.rs

* focusing on graph dir only
Related to #17

chore: remove unused things

---

common/infrastructure/Cargo.toml

Same situation as #64 
```
error[E0432]: unresolved import `tokio::select`
--> common/infrastructure/src/health/checks/local.rs:9:5
|
9 | use tokio::select;
|     ^^^^^^^^^^^^^ no `select` in the root
error: cannot determine resolution for the macro `select`
--> common/infrastructure/src/health/checks/local.rs:102:17
|
102 |                 select! {
|                 ^^^^^^
|
= note: import resolution is stuck, try simplifying macro imports
```

build(fix): Enable feature to fix build within child workspace

---

common/src/cpe22.rs
common/src/package/mod.rs
server/src/lib.rs
server/src/server/read/package.rs
server/src/server/read/vulnerability.rs

chore: removes remaining unused imports

---

common/Cargo.toml
common/src/package/mod.rs
common/src/purl.rs
graph/src/graph/advisory/advisory_vulnerability.rs
graph/src/graph/advisory/mod.rs
graph/src/graph/package/mod.rs
graph/src/graph/package/package_version.rs
graph/src/graph/package/qualified_package.rs
graph/src/graph/sbom/mod.rs
graph/src/graph/sbom/spdx.rs
server/Cargo.toml
server/src/server/mod.rs
server/src/server/read/package.rs

Resolves #6 
Converting strings to purl's is fallible, so we need to implement `TryFrom` instead of `From`. Changing the fn args to `TryFrom<Purl, Error=...>` became verbose, so this PR changes them to `Purl`, forcing callers to try the conversion beforehand.

Convert fn's to take Purl's to simplify fallible string conversions

---

common/auth/src/client/inject.rs
modules/importer/src/endpoints.rs
modules/importer/src/service.rs
modules/importer/src/test.rs
rust-toolchain.toml

The reason for updating to Rust 1.76.0 was the introduction of `inspect_err`, which I find super helpful (also in this case):
```rust
operation().
.inspect_err(|err| {
log::info!("err: {err:?}");
})
```

fix: add test for optimistic locking and fix it

---

entity/src/lib.rs
entity/src/vulnerability.rs
entity/src/vulnerability_description.rs
graph/src/graph/advisory/mod.rs
graph/src/graph/mod.rs
graph/src/graph/vulnerability.rs
ingestors/Cargo.toml
ingestors/src/cve/cve_record/v5.rs
ingestors/src/cve/loader.rs
ingestors/src/lib.rs
migration/src/lib.rs
migration/src/m0000011_create_vulnerability.rs
migration/src/m0000012_create_vulnerability_description.rs

Provide a handy method for getting a new db transaction. CVE record importer uses transactions and sets title/description. A few small renames of system->graph.

Add `title` and `description` to Vulnerability models and entities.

---

modules/importer/Cargo.toml
modules/importer/src/test.rs

Use test-log to handle logger init stuff

---

common/src/db.rs
graph/src/graph/advisory/advisory_vulnerability.rs
graph/src/graph/advisory/csaf/mod.rs
graph/src/graph/advisory/mod.rs
graph/src/graph/cpe22.rs
graph/src/graph/mod.rs
graph/src/graph/package/mod.rs
graph/src/graph/package/package_version.rs
graph/src/graph/package/qualified_package.rs
graph/src/graph/sbom/mod.rs
graph/src/graph/sbom/spdx.rs
graph/src/graph/vulnerability.rs
ingestors/src/advisory/osv/loader.rs
ingestors/src/cve/loader.rs

Add type constraints to make using transactions a bit easier. A `Transactional::Some(_)` owns its transaction, reducing the things you need to hang onto.
A `Transactional::Some(_)` is provided ready-to-eat from Graph::transaction(). A `()` can be used for non-transactional as shorthand for `Transactional::None`.

Replace a few more Into<Purl>'s hither and yon.

---

Cargo.lock
entity/src/cvss3.rs
migration/src/m0000033_create_cvss3.rs
modules/graph/src/graph/advisory/advisory_vulnerability.rs
modules/graph/src/graph/advisory/mod.rs
modules/ingestor/src/service/advisory/osv/loader.rs

Given that a single advisory can speak towards multiple vulnerabilities, the severity should be associated with the join of the two two entities.

Move CVSS scoring from `Advisory` down to `AdvisoryVulnerability`.

---

Cargo.lock
entity/Cargo.toml
entity/src/advisory.rs
migration/src/m0000060_create_advisory.rs
modules/graph/src/graph/advisory/mod.rs
modules/ingestor/src/service/advisory/osv/loader.rs

* published
* modified
* withdrawn
Ingest those from OSV where appropriate.

Add three columns to advisory:

---

Cargo.toml
common/Cargo.toml
common/auth/Cargo.toml
common/infrastructure/Cargo.toml
entity/Cargo.toml
importer/Cargo.toml
modules/graph/Cargo.toml
modules/importer/Cargo.toml
modules/ingestor/Cargo.toml
server/Cargo.toml
trustd/Cargo.toml

chore: cargo deps using workspace=true instead of path

---

entity/src/package_relates_to_package.rs

To my understanding that should be a composite primary key:
https://github.com/trustification/trustify/blob/3f0719b4bcae5f10561a27256bff80abb9466a2e/migration/src/m0000220_create_package_relates_to_package.rs#L58-L64
And the docs seem to require the attribute for all fields of that key:
https://www.sea-ql.org/SeaORM/docs/generate-entity/entity-structure/#composite-key

fix: properly define primary key

---

Cargo.lock
Cargo.toml
modules/ingestor/Cargo.toml
modules/ingestor/src/service/advisory/csaf/loader.rs
modules/ingestor/src/service/advisory/osv/loader.rs
modules/ingestor/src/service/cve/loader.rs
modules/ingestor/src/service/hashing.rs

- Added the option to use any `ring::digest::Algorithm` for `trustify_module_ingestor::service::hashing::HashingRead` - defaulting to SHA384 (previously SHA256, see #161)
- Changed associated functions to match `ring::digest::Digest` behavior - mainly `.finish()`, that takes ownership of main to prevent any misuse.
- Added tests for hashing / reading.

feat(ingestor): default to sha384 hashing and allow for algorithm customization

---

docs/design/importer.md

This is a first test on how we could do design docs as part of the code. At least, closer to the code.
I think it works reasonably well. My expectation would be that the docs might not be fleshed out, might have some gaps in less relevant areas, but must be correct!
I am not sure about the file system structure. Those docs could also go into their respective modules folders.
Rendered version: https://github.com/ctron/trustify/blob/feature/design_docs_1/docs/design/importer.md

docs: first try for some design docs

---

Cargo.lock
Cargo.toml
common/auth/src/authenticator/validate.rs
common/auth/src/client/mod.rs
common/auth/src/client/provider/openid.rs
modules/importer/Cargo.toml
modules/importer/src/server/common/filter.rs
modules/importer/src/server/csaf/report.rs
modules/importer/src/server/csaf/storage.rs
modules/importer/src/server/sbom/report.rs
modules/importer/src/server/sbom/storage.rs

This updates dependencies to ones using http 1 (over http 0.2), reducing the number of duplicates, like reqwest.

chore: upgrade dependencies

---

Cargo.lock
Cargo.toml
modules/fetch/src/endpoints/package.rs
modules/ingestor/src/endpoints/advisory.rs
modules/ingestor/src/endpoints/sbom.rs

Fixes: #235
This allows us to keep our OpenApi docs modular, i.e. merge now honors http methods.

fix: swagger-ui by pulling in utoipa upstream fix

---

modules/ingestor/src/endpoints/advisory.rs

Resolves https://github.com/trustification/trustify/issues/241

Rename /api/v1/advisory/{id} by /api/v1/advisory/{id}/download

---

README.md

I acknowledge the need to see the current status of the UI in relation to the backend and since https://github.com/trustification/trustify/pull/176 is taking some time to order things, I decided to add instruction to the Readme.md file so anyone can start the UI container image and play with it.
I will continue working on https://github.com/trustification/trustify/pull/176 though

Add instructions for running UI using the container image

---

entity/src/vulnerability.rs
migration/src/m0000040_create_vulnerability.rs
modules/fetch/src/endpoints/advisory.rs
modules/fetch/src/endpoints/vulnerability.rs
modules/fetch/src/model/vulnerability.rs
modules/fetch/src/service/advisory.rs
modules/fetch/src/service/vulnerability.rs
modules/ingestor/src/graph/advisory/mod.rs
modules/ingestor/src/graph/vulnerability/mod.rs
modules/ingestor/src/service/advisory/csaf/loader.rs
modules/ingestor/src/service/advisory/osv/loader.rs
modules/ingestor/src/service/cve/cve_record/v5.rs
modules/ingestor/src/service/cve/loader.rs
modules/ingestor/src/service/format.rs

Hydrate details into a Vulnerability even if ingested after first light reference. Add some error-reporting if format auto-detection doesn't. Ensure `vulnerabilities` field is included, even if an empty array.

Thicken up the Vulnerability DTOs.

---

README.md
docs/design/fetch-service.md
docs/design/importer.md
docs/glossary.md
modules/README.md
modules/fetch/README.md
modules/importer/README.md

* Fixes some typos
* Standardizing shell usage for command code blocks (as in readme) instead of bash
* changed _ to * for emphasis (weirdo md lint says _ is bad)

chore: markdown lints

---

model/src/advisory/details/advisory_vulnerability.rs
model/src/vulnerability/details/vulnerability_advisory.rs
model/src/vulnerability/mod.rs
modules/vulnerability/src/endpoints/test.rs

Ensure dates are serialized in a non-array format as expected by the UI. Tests for the above.
Also, include the assertions we bothered to calculate.

Ensure dates are included in fully-ingested vulnerabilities.

---

Cargo.lock
Cargo.toml
entity/src/organization.rs
model/src/advisory/details/advisory_vulnerability.rs
model/src/advisory/details/mod.rs
model/src/advisory/mod.rs
model/src/advisory/summary.rs
model/src/lib.rs
model/src/organization/details/mod.rs
model/src/organization/mod.rs
model/src/organization/summary.rs
model/src/vulnerability/details/mod.rs
model/src/vulnerability/details/vulnerability_advisory.rs
model/src/vulnerability/mod.rs
model/src/vulnerability/summary.rs
modules/advisory/src/endpoints/mod.rs
modules/advisory/src/endpoints/test.rs
modules/advisory/src/service/mod.rs
modules/organization/Cargo.toml
modules/organization/src/endpoints/mod.rs
modules/organization/src/endpoints/test.rs
modules/organization/src/lib.rs
modules/organization/src/service/mod.rs
modules/organization/src/service/test.rs
modules/vulnerability/src/endpoints/mod.rs
modules/vulnerability/src/endpoints/test.rs
modules/vulnerability/src/service/mod.rs
server/Cargo.toml
server/src/lib.rs
server/src/openapi.rs

- Includes advisories issued by an organization.
- Simplify some of the from_entity ish to avoid unnecessary Result<Option<T>>
- Clean up API paths on openapi, etc, a bit.

Add support for Organization-related endpoints.

---

Cargo.lock
Cargo.toml

This should eliminate the NPM builds.

Use the static build of the trustify-ui

---

.github/workflows/release.yaml
Cargo.lock
Cargo.toml
Cross.toml
trustd/Cargo.toml

This makes the release build multi-arch capable for the following targets:
* MacOS 12 for Intel
* MacOS 14 for Mx
* Windows
* Linux (GNU & MUSL) (amd64 & aarch64)
The release will look like this: https://github.com/ctron/trustify/releases/tag/v0.0.0-alpha.1

ci: add a multi-arch release workflow

---

.github/scripts/map-users/main.mjs
.github/scripts/map-users/test.mjs
.github/workflows/rita-request-review.yaml

Right now, when adding multiple reviewers on a PR, this triggers a repeated invocation of the event handler (one for each reviewer). It also send out an event for each reviewer, each time. So the number of messages sent is x².
This change fixes this and updates a few github actions in the process.

Fix wall of notifications when adding multiple reviewers to a PR

---

.github/scripts/Containerfile
Cargo.lock
common/Cargo.toml
common/auth/Cargo.toml
common/infrastructure/Cargo.toml
common/src/db/mod.rs
cvss/Cargo.toml
entity/Cargo.toml
integration-tests/Cargo.toml
migration/Cargo.toml
modules/fundamental/Cargo.toml
modules/importer/Cargo.toml
modules/ingestor/Cargo.toml
modules/storage/Cargo.toml
modules/ui/Cargo.toml
server/Cargo.toml
trustd/Cargo.toml

This change fixes some build issues:
* openssl is not part of ubi-micro, this will be installed now too
* postgresql-embedded is forced into "bundled" mode, which doesn't work with offline builds. It is still the default, but there's a way to opt-out now.
* I forgot to uptick the versions during the last release, this fixes it.

Fix some build issues

---

server/src/lib.rs

Looks like using `id` with `clap` skips the default renaming.
Also, order the args to that the sections stay together.

chore: fixup UI arguments

---

modules/importer/src/endpoints.rs
modules/importer/src/server/csaf/mod.rs

Fix the issue that the CSAF importer should either accept a full URL, or use the CSAF lookup.

fix: accept either domain or full URL

---

common/src/db/func.rs
common/src/db/limiter.rs
common/src/db/query.rs
entity/src/lib.rs
migration/src/lib.rs
migration/src/m0000315_create_cvss3_scoring_function.rs
migration/src/m0000315_create_cvss3_scoring_function.sql
modules/fundamental/src/advisory/model/summary.rs
modules/fundamental/src/advisory/service/mod.rs
modules/fundamental/src/advisory/service/test.rs

Provide enough escape-hatches around filterin/sorting to do my evil deeds. Do some evil deeds in SQL to allow sorting/filtering by synthetic `average_score` on advisories. Do even more evil, by writing entirely too many SQL functions. Lay in appropriate DOWN migration for cvss3 scoring functions.

Allow calculation of CVSS3 score using SQL functions, like a madman.

---

Cross.toml

When building with cross, a container image using Ubuntu 16.04 is being used. This seems to be the cause for creating a binary which will segfault (or run into other such failures) when running on aarch64.
Using Ubuntu 20.04 does not produce this issue.
Also see:
* https://github.com/cross-rs/cross/issues/1512
* https://github.com/rust-lang/git2-rs/issues/1057
---
This might be a better way than https://github.com/trustification/trustify/pull/387 … as it doesn't add new code to work around this, but uses the existing, which should work anyway.
On the other side: Having the other PR might offer a quick way out should this occur on other targets. However, I am not sure it's that likely and worth it.

fix: use newer container to fix/workaround segfault in libgit2

---

Cargo.lock
common/src/id.rs
common/src/lib.rs
modules/fundamental/Cargo.toml
modules/fundamental/src/advisory/endpoints/mod.rs
modules/fundamental/src/advisory/endpoints/test.rs
modules/fundamental/src/advisory/model/mod.rs
modules/fundamental/src/advisory/service/mod.rs
modules/fundamental/src/advisory/service/test.rs
modules/fundamental/src/error.rs
modules/fundamental/src/lib.rs
modules/fundamental/src/sbom/endpoints/mod.rs
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/sbom/service/sbom.rs
modules/fundamental/src/test.rs
modules/ingestor/src/service/advisory/csaf/loader.rs
modules/ingestor/src/service/advisory/osv/loader.rs
modules/ingestor/src/service/cve/loader.rs
modules/ingestor/src/service/format.rs
modules/ingestor/src/service/mod.rs
modules/ingestor/src/service/sbom/cyclonedx.rs
modules/ingestor/src/service/sbom/spdx.rs
modules/storage/src/service/dispatch.rs
modules/storage/src/service/fs.rs
modules/storage/src/service/mod.rs

Fix #394: Before downloading the actual content, we look up the sha256 digest from the database and use that to fetch the content from the storage. This is done for advisories, but also for SBOMs.
Also:
* When uploading a document, return the `Id` of the database instead of some ID field from the document
* Rename `HashOrUuidKey` to `Id`
* Make it clearer what key/id means for the storage (`StorageKey`)

Look up documents before retrieving, improve id/key naming conventions

---

common/src/db/query.rs
entity/src/cvss3.rs
migration/src/lib.rs
migration/src/m0000325_create_cvss3_severity_column.rs
migration/src/m0000325_create_cvss3_severity_column.sql
modules/fundamental/src/advisory/model/summary.rs
modules/fundamental/src/advisory/service/mod.rs
modules/fundamental/src/advisory/service/test.rs
modules/ingestor/src/graph/advisory/advisory_vulnerability.rs

Add a cvss3.severity column with that enum.
Calculate it in a migration.
Adjust Query API to support enums (Value->ValueOrSimpleExpr for envalue()) Add SQL function to calculate severity from score (for non-stored avg(score)) Add average_severity to the query.

Add a cvss3_severity enum (none, low, medium, high, critical)

---

Cargo.lock
Cargo.toml
common/src/db/mod.rs
trustd/src/db.rs

Sets embedded postgres config to preload **pg_stat_statements** lib
```
shared_preload_libraries=pg_stat_statements
```
so we can invoke
```
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
```
when _pm-mode_ is engaged, which installs **pg_stat_statements** into **trustify** embedded pg database.
This is a minimal first effort - in the future we may want to do more - such as pass in env var to set pg configs, etc ... though as _pm-mode_ is purely developmental I stopped there.
**Note**: Bumped **postgresql_embedded**=0.10.1, **postgresql_archive**=0.10.1

Enable pg_stat_statements postgres extension when in pm-mode

---

common/src/db/limiter.rs
common/src/db/mod.rs
common/src/db/query.rs
common/src/db/test.rs
common/src/id.rs
common/src/lib.rs
common/src/model.rs
common/src/purl.rs
common/src/time.rs

This should enable filtering and sorting of enum fields like `severity` by translating them into queries for `score` instead.

feat: add ability to translate queries

---

Cargo.lock

The current approach for Trustify is to point to a tag (of the trustify-ui). However, the Cargo.lock saves a specific commit to which it will point, therefore it needs manual update process

Upgrade ui tag/commit

---

README.md

The backend should be started through:
```shell
cargo run --bin trustd
```
The the docker|podman can run to have the very latest version of the UI

Update README.md to run ui through docker|podman

---

modules/importer/src/server/cve/mod.rs
modules/importer/src/server/osv/mod.rs

The reports for CVE and OSV always show zero items, because the report was not updated with the number of processes items. This PR fixes this.

fix: count items being processed for osv and cve

---

Cargo.lock
trustd/Cargo.toml
trustd/tests/tests.rs

I'm running PM-mode just to have access to DB.
And then running devmode with no auth and a different port and doing the basic requests

test: ensuring the embedded UI works

---

.github/workflows/ci.yaml
common/src/db/mod.rs
integration-tests/src/sbom/test/cyclonedx.rs
integration-tests/src/sbom/test/perf.rs
integration-tests/src/sbom/test/spdx.rs
modules/fundamental/src/sbom/service/sbom.rs
modules/ingestor/src/graph/purl/mod.rs
trustd/tests/tests.rs

This test has problems:
- it takes too long (it never completes in my local env)
- it leaves .trustify dirs behind
- it shells out to a binary
- it uses a hardcoded port
- it makes requests of URL's that don't exist
- it's not clear that it affirms the fix for #422 
I recommend it be moved beneath `server/` and refactored to use TestRequest.

Ignoring embedded UI test

---

modules/fundamental/src/package/model/details/package_version.rs
modules/fundamental/src/package/service/mod.rs
modules/fundamental/src/vulnerability/model/details/vulnerability_advisory.rs
modules/fundamental/src/vulnerability/service/mod.rs
modules/fundamental/src/vulnerability/service/test.rs

Also, bring towards Vulnerability details, including stanzas akin to Note: the set of possible statuses is unbound, but may include at least some intrinsic ones, such as "affected", "not_affected", and "fixed".
Versions are denoted as one of:
- A singular version without delimiters.
- A range, using [ and ] to denote *inclusive* and ( and ) as exclusive.
- These can be mixed within a single range, to indicate that the range is half-open, possibly. (Inclusive of the low side, but exclusive to the high side)
- For any range, low or high may be absent, indicating unbounded/infinite.
- If no versions are provided, a `*` is provided, indicating _all versions_ are represented by that status.
```
"statuses": {
"affected": [
{
"package": {
"uuid": "9adb7324-89b7-5fe0-a556-23218e39ebf3",
"purl": …
```

Bring forward status assertions to package-versions.

---

common/src/db/query.rs
modules/fundamental/src/sbom/endpoints/mod.rs
modules/fundamental/src/sbom/endpoints/test.rs
modules/fundamental/src/sbom/service/sbom.rs

Relates to #434 as a test for filtering packages was added

feat: enable backslash to escape operators in filter expressions

---

modules/fundamental/src/vulnerability/service/test.rs

For the RUSTSEC advisory, statuses of "fixed" and "affected" shall be present. For the CVE advisory for the same vulnerability, no statuses are expected.

Test ensuring that the happy-path has correct statuses.

---

common/src/id.rs
entity/src/advisory.rs
entity/src/labels.rs
entity/src/sbom.rs
modules/fundamental/src/advisory/endpoints/label.rs
modules/fundamental/src/advisory/endpoints/mod.rs
modules/fundamental/src/advisory/endpoints/test.rs
modules/fundamental/src/advisory/model/mod.rs
modules/fundamental/src/advisory/model/summary.rs
modules/fundamental/src/advisory/service/mod.rs
modules/fundamental/src/error.rs
modules/fundamental/src/sbom/endpoints/label.rs
modules/fundamental/src/sbom/endpoints/mod.rs
modules/fundamental/src/sbom/endpoints/test.rs
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/sbom/service/label.rs
modules/fundamental/src/sbom/service/mod.rs
modules/fundamental/src/sbom/service/sbom.rs

Coming from @bobmcwhirter's suggestion of making the labelling a two-step process: https://matrix.to/#/!heUmIqxVhZejiSjzVu:matrix.org/$VtbkZ9oC8eeQqzDLlsCes5sMWQRiBZrNwnhf231UZZ4?via=matrix.org&via=dentrassi.de 
… here is the PR to allow settings labels. I think this makes sense in any way. We can still add the ability to set initial labels once we find the best way to pass them to the backend.

Allow setting labels for advisories and SBOMs

---

etc/test-data/csaf/CVE-2024-5154.json
modules/fundamental/src/package/service/test.rs
modules/fundamental/src/vulnerability/model/details/vulnerability_advisory.rs
modules/ingestor/src/graph/advisory/advisory_vulnerability.rs
modules/ingestor/src/service/advisory/csaf/creator.rs

In the status-builder, ignore qualifiers, impl PartialEq where necessary. In the vuln fetching, add a `distinct`.

Reduce duplicate status ingestions.

---

Cargo.lock
server/Cargo.toml
server/src/lib.rs

Add test affirming our server routing configuration

---

entity/src/advisory.rs
entity/src/advisory_vulnerability.rs
entity/src/cvss3.rs
entity/src/cvss4.rs
entity/src/package_status.rs
entity/src/vulnerability.rs
entity/src/vulnerability_description.rs
migration/src/lib.rs
migration/src/m0000395_alter_vulnerability_pk.rs
migration/tests/tests.rs
modules/fundamental/src/advisory/model/details/advisory_vulnerability.rs
modules/fundamental/src/advisory/model/details/mod.rs
modules/fundamental/src/advisory/model/mod.rs
modules/fundamental/src/advisory/model/summary.rs
modules/fundamental/src/package/model/details/package_version.rs
modules/fundamental/src/package/model/details/qualified_package.rs
modules/fundamental/src/vulnerability/endpoints/test.rs
modules/fundamental/src/vulnerability/model/details/mod.rs
modules/fundamental/src/vulnerability/model/details/vulnerability_advisory.rs
modules/fundamental/src/vulnerability/model/mod.rs
modules/fundamental/src/vulnerability/model/summary.rs
modules/fundamental/src/vulnerability/service/mod.rs
modules/graphql/src/vulnerability.rs
modules/ingestor/src/graph/advisory/advisory_vulnerability.rs
modules/ingestor/src/graph/advisory/mod.rs
modules/ingestor/src/graph/vulnerability/mod.rs
modules/ingestor/src/service/advisory/csaf/creator.rs
modules/ingestor/src/service/advisory/csaf/loader.rs
modules/ingestor/src/service/advisory/osv/loader.rs

Move vulnerability table to use the identifier as the natural primary key.
Adjust API service to vuln.identifier-centricism.
Fix queries since vulnerabilities table may not have a related row.
Fix up other queries.
Rename vuln.identifier -> vuln.id
Use two-stage search for vulnerabilities.
Fixes #471

Vuln pk try 2

---

migration/src/lib.rs
migration/src/m0000410_labels_index.rs
modules/fundamental/src/advisory/endpoints/test.rs
modules/importer/src/model/mod.rs
modules/importer/src/server/csaf/mod.rs
modules/importer/src/server/csaf/storage.rs
modules/importer/src/server/cve/mod.rs
modules/importer/src/server/osv/mod.rs
modules/importer/src/server/sbom/mod.rs
modules/importer/src/server/sbom/storage.rs
modules/importer/src/test.rs
modules/ingestor/src/service/advisory/csaf/loader.rs
modules/ingestor/src/service/advisory/osv/loader.rs
modules/ingestor/src/service/cve/loader.rs
modules/ingestor/src/service/sbom/cyclonedx.rs
modules/ingestor/src/service/sbom/spdx.rs
server/src/sample_data.rs

This PR adds:
* The ability to set labels on the importer which get applied to the imported documents: let the user decide, always comes in handy
* A `type` label to each document, reflecting the document type (csaf, osv, …): have the UI distinguish between document types when the name/ID is the same (like CVE IDs as names)
* A `file` label, containing the name of the file, relative to the source, that was ingested: prepare for getting all versions (history) of the same file

feat: add more labels to imported documents, allow user defined labels

---

README.md

The current command seems to assume we have the binaries already created, however considering it is the Readme file I was expecting to just copy and paste commands to be able to follow the instructions

task: enhance podman-compose commands in README.md

---

common/src/cpe.rs
entity/src/package_relates_to_package.rs
entity/src/sbom.rs
modules/fundamental/src/vulnerability/model/details/vulnerability_advisory.rs
modules/fundamental/src/vulnerability/service/test.rs

All SBOMs referencing purls that have a status from an advisory are evaluated. If a given SBOM resolves to a set of statuses (which may be a combination of statuses, such as "fixed" *and* "not_affected") those should be considered the absolute status of that SBOM _per that advisory_.
For an SBOM that contains *no* status set, the status shall be interpreted as _possibly affected_ but otherwise not asserted either way.

Return simplified SBOM status for a given vulnerability.

---

.github/workflows/release.yaml
.gitignore

Also: use GITHUB_TOKEN for `cargo binstall` to avoid GH API rate limits
Closes #534

ci: generate cyclonedx sboms during the build

---

entity/src/cpe.rs
modules/fundamental/src/vulnerability/endpoints/test.rs
modules/fundamental/src/vulnerability/service/mod.rs
modules/ingestor/src/graph/organization.rs
modules/ingestor/src/graph/product/mod.rs
modules/ingestor/src/graph/vulnerability/mod.rs
modules/ingestor/src/service/advisory/csaf/creator.rs
modules/ingestor/src/service/advisory/csaf/loader.rs
modules/ingestor/src/service/advisory/osv/loader.rs
modules/ingestor/tests/csaf.rs
modules/ingestor/tests/cve.rs
modules/ingestor/tests/osv.rs
modules/ingestor/tests/spdx.rs

This PR adds a few tests for re-ingesting documents. It also fixes issues alongside those. Most notably, it auto-creates vulnerabilities and switches the creation of those to an upsert model.

Ingestion fixes, auto-create vulnerabilities using upsert

---

modules/fundamental/src/advisory/model/details/advisory_vulnerability.rs
modules/fundamental/src/vulnerability/model/details/mod.rs
modules/fundamental/src/vulnerability/model/mod.rs
modules/fundamental/src/vulnerability/service/test.rs
modules/ingestor/src/graph/vulnerability/mod.rs

Fixes #543
If we have the CVE ingested, i.e. a Vulnerability record, we'll use its data and declare it "normative". Otherwise, we'll use the non-normative data from the advisory.

fix: remove non-normative data from advisory vulnerability

---

migration/Cargo.toml

I found this while using this tool https://github.com/taiki-e/cargo-hack?tab=readme-ov-file#--each-feature
"_This is useful to check that each feature is working properly_"
The build error: https://gist.github.com/helio-frota/a35c47dda223e471b8b307ecdc991c47
As `sea-orm-migration` https://crates.io/crates/sea-orm-migration/0.12.15/dependencies is using `sea-orm` as dependency, I suspect that in some circumstance it needs to be enabled. 
although it is not in any of these three: https://doc.rust-lang.org/cargo/reference/resolver.html?highlight=feature#feature-resolver-version-2

chore: enables with-uuid feature

---

Cargo.lock
common/src/cpe.rs
common/src/db/mod.rs
common/src/db/multi_model.rs
entity/src/cpe.rs
entity/src/purl_status.rs
entity/src/qualified_purl.rs
entity/src/sbom.rs
entity/src/version_range.rs
modules/fundamental/src/purl/model/mod.rs
modules/fundamental/src/purl/model/summary/purl.rs
modules/fundamental/src/purl/model/summary/versioned_purl.rs
modules/fundamental/src/sbom/endpoints/mod.rs
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/sbom/service/mod.rs
modules/fundamental/src/sbom/service/sbom.rs
modules/fundamental/src/sbom/service/test.rs
modules/fundamental/src/vulnerability/model/details/vulnerability_advisory.rs
modules/fundamental/tests/sbom/cyclonedx.rs
modules/fundamental/tests/sbom/graph.rs
modules/fundamental/tests/sbom/reingest.rs
modules/fundamental/tests/sbom/spdx.rs

`/api/v1/sbom/{id}` produces a fuller SBOM details which includes SBOM -> advisory -> vulnerability information, for all statuses, which may include `fixed`, `not_affected`, `known_affected` etc.

Include vulnerability information in SBOM details.

---

modules/fundamental/src/advisory/endpoints/test.rs
modules/fundamental/src/purl/service/test.rs
modules/fundamental/src/sbom/endpoints/test.rs
modules/fundamental/tests/sbom/mod.rs
modules/fundamental/tests/sbom/reingest.rs
modules/fundamental/tests/sbom/spdx.rs
modules/ingestor/src/service/advisory/csaf/loader.rs
modules/ingestor/src/service/advisory/cve/loader.rs
modules/ingestor/src/service/advisory/osv/loader.rs
modules/ingestor/src/service/format.rs
modules/ingestor/src/service/sbom/cyclonedx.rs
modules/ingestor/src/service/sbom/spdx.rs
test-context/src/lib.rs

Using .cargo/config.toml creating an env var
called WORKSPACE_ROOT

chore: avoiding relative path

---

Cargo.lock
server/Cargo.toml
server/src/lib.rs
trustd/src/main.rs
trustd/src/openapi.rs

Usage:
```
trustd openapi export --file test.json
```
* defaults to json format
* exports as yaml if file ends with ‘yaml’ or ‘yml’

feat: add trustd subcommand to export openapi spec

---

modules/fundamental/src/advisory/endpoints/mod.rs
modules/fundamental/src/advisory/endpoints/test.rs
modules/fundamental/src/advisory/service/test.rs
modules/fundamental/src/organization/endpoints/test.rs
modules/fundamental/src/organization/service/test.rs
modules/fundamental/src/product/endpoints/test.rs
modules/fundamental/src/product/service/test.rs
modules/fundamental/src/purl/endpoints/test.rs
modules/fundamental/src/purl/service/test.rs
modules/fundamental/src/sbom/endpoints/mod.rs
modules/fundamental/src/sbom/endpoints/test.rs
modules/fundamental/src/sbom/service/sbom.rs
modules/fundamental/src/test.rs
modules/fundamental/src/vulnerability/endpoints/test.rs
modules/fundamental/tests/sbom/graph.rs
modules/fundamental/tests/sbom/reingest.rs
modules/fundamental/tests/sbom/spdx.rs

Expanded CallService to return json and added a `caller` helper to return an impl of it, i.e. an App::new configured with the fundamental endpoints. Replaced the `with_upload` async closures with calls to `caller` and `ctx.ingest_document`. Added an explicit test for SBOM uploading in lieu of `with_upload`.

refactor: simplify tests by incorporating more TrustifyContext

---

Cargo.lock
modules/fundamental/Cargo.toml

This allows the uuid paths params to have the schema set.

Enable the utopia uuid feature 

---

modules/importer/src/endpoints.rs

Part of the fix for #580 
Fixes errors like:
```
- attribute paths.'/api/v1/importer/{name}'(put).parameters.[if-match].content is missing`
```

fix: define the schema type of the if-match headers.

---

.cargo/config.toml
.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
xtask/Cargo.toml
xtask/src/main.rs
xtask/src/openapi.rs

Run with:
```
cargo xtask validate-openapi
```

Add cargo xtask validate-openapi command that can be used to validate the generated openapi spec.

---

migration/src/lib.rs
migration/src/m0000475_improve_version_comparison_fns.rs
migration/src/m0000475_improve_version_comparison_fns/semver_cmp.sql
migration/src/m0000475_improve_version_comparison_fns/semver_version_matches.sql
migration/src/m0000475_improve_version_comparison_fns/version_matches.sql
migration/tests/semver.rs

- use bigger ints for jackholes who version stuff like 202410298675309.
- if a version cmp fails (because a sha:xxx "version" was given) don't fail, just false.
In theory fixes #466.

Improve the SQL version comparisons:

---

common/src/db/mod.rs
trustd/src/db.rs

Set the embedded_pg to more 'modern' settings:
From trustify we set
* db max conns = 300
* db min conns = 75
and in pg config
* **max_connections**=500
which lets the database 'breath'.
Additionally set **random_page_cost** to 1.1 because we all have SSD these days and the default setting of 4 is for _spinning rust_. There are a lot of pg configs that have dramatically conservative defaults which we can revisit but wanted to establish a baseline for the embedded_pg.

chore: tweak embedded database settings

---

etc/test-data/spdx/double-ref.json
etc/test-data/spdx/loop.json
etc/test-data/spdx/self-package.json
etc/test-data/spdx/self.json
modules/fundamental/src/sbom/endpoints/mod.rs
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/sbom/service/sbom.rs
modules/fundamental/tests/sbom/spdx.rs
modules/fundamental/tests/sbom/spdx/corner_cases.rs
modules/fundamental/tests/spdx.rs
test-context/src/lib.rs

This fixes the two issues of https://github.com/trustification/trustify/discussions/555 but removing duplicated during the conversion and by renaming the enum variant to `All`, which better reflects what it currently does.

Add some corner case tests for SPDX, and fix a discovered issue

---

migration/src/lib.rs
migration/src/m0000500_fix_sbom_node_fks.rs
modules/ingestor/src/graph/sbom/mod.rs

Drop the node_id constrains since they modeled inheritance, not ownership, replace with sbom_id cascading constraints that do model ownership.
And then fix ingestion so that the sbom record is created before the sbom_node record, since the sbom record owns it.

fix: sbom_node FK constraints

---

README.md
modules/importer/src/server/sbom/mod.rs

This PR tries to enable csaf importer to use file source and additionally to unify how sbom and csaf importers handle this case.
It should allow enable local file system importers like
```
http POST localhost:8080/api/v1/importer/ds1-csaf "csaf[source]=file:///Users/dejanb/workspace/github.com/trustification/trustification/data/ds1/csaf/" "csaf[disabled]:=false" "csaf[period]=30s" "csaf[v3Signatures]:=true"
http POST localhost:8080/api/v1/importer/ds1-sbom "sbom[source]=file:///Users/dejanb/workspace/github.com/trustification/trustification/data/ds1/sbom/" "sbom[disabled]:=false" "sbom[period]=30s" "sbom[v3Signatures]:=true"
```

fix: remove usage of FileSource and document how to use csaf walker to ingest local files

---

Cargo.lock
common/src/db/mod.rs
modules/fundamental/Cargo.toml
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/sbom/model/mod.rs
modules/graphql/src/endpoints.rs
modules/graphql/src/lib.rs
modules/graphql/src/sbom.rs
modules/graphql/src/sbomstatus.rs
server/src/lib.rs

Relates to https://issues.redhat.com/browse/TC-1643
Because GraphQL types have to be either a primitive type or an already defined type the following two types are not yet defined and have been skipped for now :
- `StatusContext`
- `PurlSummary` of `SbomPackage`
`StatusContext` will be address using a wrapper : https://async-graphql.github.io/async-graphql/en/define_enum.html#wrapping-a-remote-enum
For the latter, this will imply defining all the sub-structures.
Here is an example of this query for a given SBOM uuid :
```
"data": {
"cvesBySbom": [
{
"vulnerabilityId": "CVE-2024-2700",
"status": "not_affected",
"packages": [
{
"id": "SPDXRef-a8990972-32d2-44a6-b479-743788c3454a",
"name": "virtual-list",
"version": "24.0.5"
},
{
"id": "SPDXRef-e09632af-8ea9-43fa-a4ff-d45c24a6aa80",
"name": …
```

GraphQL: Retrieve CVEs by Sbom with impacted packages

---

common/src/db/multi_model.rs
entity/src/cvss3.rs
entity/src/vulnerability.rs
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/sbom/service/sbom.rs
modules/fundamental/src/vulnerability/model/details/mod.rs
modules/fundamental/src/vulnerability/model/details/vulnerability_advisory.rs
modules/fundamental/src/vulnerability/model/mod.rs
modules/fundamental/src/vulnerability/service/mod.rs
modules/fundamental/src/vulnerability/service/test.rs

and learning the statuses of each SBOM related.
Allow multi-model queries to include the same table/model multiple times with appropriate aliasing.

Remove queries from within inner loops, for vulnerability details

---

Cargo.lock
modules/fundamental/Cargo.toml
modules/fundamental/src/product/model/details.rs
modules/fundamental/src/product/model/mod.rs
modules/fundamental/src/product/model/summary.rs

By using load_many and load_one patterns we can now avoid querying in the loop

Improve performance of fetching product summaries

---

Cargo.lock
Cargo.toml
modules/fundamental/Cargo.toml
modules/fundamental/benches/bench.rs

if you run `cargo bench` with this patch you can then 
```
open target/criterion/report/index.html
```
to view the benchmark report.  If you re-run the benchmark, it will show you perf difference compared to the previous run.

Adding a criterion based benchmark for csaf ingestion.

---

modules/ingestor/src/graph/sbom/spdx.rs

We now collect that message and report it either through the ingestion result or the importer report. Shouting it out on the applications log channels no longer makes sense.

chore: lower to debug

---

migration/src/m0000510_create_maven_cmp_fns.rs
modules/storage/src/service/fs.rs
modules/storage/src/service/mod.rs
modules/storage/src/service/s3.rs
modules/storage/src/service/temp.rs

Now both the FS and S3 backends share the same logic to create a temp file before permanently storing its content keyed by its digest. This enables a single S3 write per document rather than the previous potentially expensive write/copy/delete.
Relates to #621

feat: refactor temp file creation to reduce S3 usage

---

xtask/src/openapi.rs

Closes #659 
```
➜  trustify git:(foo) ✗ cargo xtask validate-openapi --export
Compiling xtask v0.1.0-alpha.13 (/home/heliofrota/Desktop/tc/trustify/xtask)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 13.96s
Running `target/debug/xtask validate-openapi --export`
Writing openapi.yaml to "openapi_yaml"
Writing openapi.yaml to "/tmp/openapi.yaml"
Validating spec (/src/openapi.yaml)
Warnings:
- Unused model: AdvisoryVulnerabilityAssertions
- Unused model: Assertion
- Unused model: Uuid
[info] Spec has 3 recommendation(s).
```
I found here https://bugzilla.redhat.com/show_bug.cgi?id=1777018

chore: fix openapi validate command

---

modules/fundamental/src/advisory/model/details/mod.rs
modules/fundamental/src/advisory/model/mod.rs
modules/fundamental/src/advisory/model/summary.rs
modules/fundamental/src/organization/model/mod.rs
modules/fundamental/src/product/model/details.rs
modules/fundamental/src/product/model/summary.rs
modules/fundamental/src/purl/model/details/base_purl.rs
modules/fundamental/src/purl/model/details/purl.rs
modules/fundamental/src/purl/model/details/versioned_purl.rs
modules/fundamental/src/purl/model/summary/versioned_purl.rs
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/vulnerability/model/details/mod.rs
modules/fundamental/src/vulnerability/model/details/vulnerability_advisory.rs
modules/fundamental/src/vulnerability/model/mod.rs
modules/fundamental/src/vulnerability/model/summary.rs
openapi.yaml

openapi: simplify API consumer interface, make output fields required

---

modules/fundamental/src/purl/service/test.rs
modules/fundamental/src/sbom/endpoints/mod.rs
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/sbom/service/sbom.rs
modules/fundamental/tests/sbom/reingest.rs
openapi.yaml

This is a first attempt to refactor SBOM DTOs to be more inline with the others. 
* `SbomHead` now maps all fields from `sboms` table
* `SbomSummary` is `SbomHead`+packages
* `SbomDetails` is `SbomSummary`+advisories
* All DTOs now implement `from_entity()` pattern

fix: refactor sbom dto objects to better represent data model

---

Cargo.toml
common/Cargo.toml
common/auth/Cargo.toml
common/infrastructure/Cargo.toml
cvss/Cargo.toml
entity/Cargo.toml
migration/Cargo.toml
modules/fundamental/Cargo.toml
modules/graphql/Cargo.toml
modules/importer/Cargo.toml
modules/ingestor/Cargo.toml
modules/storage/Cargo.toml
modules/ui/Cargo.toml
openapi.yaml
server/Cargo.toml
test-context/Cargo.toml
trustd/Cargo.toml
xtask/Cargo.toml

when running cargo release [dry-run] we can see it works fine, changing only the root `Cargo.toml`
`cargo release version alpha -v`
```console
Upgrading workspace to version 0.1.0-alpha.14
[2024-08-12T10:58:24Z DEBUG cargo_release::ops::cargo] change:
--- /home/heliofrota/Desktop/tc/trustify/Cargo.toml	original
+++ /home/heliofrota/Desktop/tc/trustify/Cargo.toml	updated
@@ -20,7 +20,7 @@
]
[workspace.package]
-version = "0.1.0-alpha.13"
+version = "0.1.0-alpha.14"
edition = "2021"
publish = false
license = "Apache-2.0"
Upgrading trustify-cvss from 0.1.0-alpha.13 to 0.1.0-alpha.14 (inherited from workspace)
Upgrading trustify-migration from 0.1.0-alpha.13 to 0.1.0-alpha.14 (inherited from workspace)
Upgrading trustify-common from 0.1.0-alpha.13 to 0.1.0-alpha.14 (inherited from workspace) …
```

chore: using workspace.package to centralize configs

---

Cargo.lock
Cargo.toml
modules/fundamental/tests/sbom/spdx.rs
modules/ingestor/Cargo.toml
modules/ingestor/src/graph/sbom/spdx.rs
modules/ingestor/src/service/advisory/csaf/loader.rs
modules/ingestor/src/service/advisory/cve/loader.rs
modules/ingestor/src/service/advisory/osv/loader.rs
modules/ingestor/src/service/format.rs
modules/ingestor/src/service/mod.rs
modules/ingestor/src/service/sbom/cyclonedx.rs
modules/ingestor/src/service/sbom/spdx.rs
modules/storage/src/service/dispatch.rs
modules/storage/src/service/fs.rs
modules/storage/src/service/mod.rs
modules/storage/src/service/s3.rs
test-context/Cargo.toml
test-context/src/lib.rs

Because serde deserialization is synchronous, and because we immediately read back the bytes we store when ingesting a doc (to ensure we can), we store them in RAM before asking serde to deserialize them.
So now we deserialize through the bridge, hopefully using less RAM in the process.
Helps with #654 though I'm sure there's more to do.

feat: replace SyncAdapter with SyncIoBridge to reduce RAM usage

---

.github/workflows/ci.yaml
xtask/src/main.rs
xtask/src/openapi.rs
xtask/src/precommit.rs
xtask/src/schema.rs

* I think this should streamline the xtask commands a bit.
* `cargo xtask precommit` does: generates the schema, generates openapi, validates openapi, cargo fmt, cargo clip, and cargo check.
* the `cargo xtask openapi` command now generates and validates (it has flags to skip either).
* the `cargo xtask gnerate-schemas` now only generates the schemas.

Add `cargo xtask precommit` rename `validate-openapi` to `openapi`

---

modules/fundamental/benches/bench.rs
modules/fundamental/src/advisory/endpoints/mod.rs
modules/fundamental/src/sbom/endpoints/mod.rs
modules/fundamental/tests/sbom/reingest.rs
modules/importer/src/runner/clearly_defined/mod.rs
modules/importer/src/runner/csaf/storage.rs
modules/importer/src/runner/cve/mod.rs
modules/importer/src/runner/osv/mod.rs
modules/importer/src/runner/sbom/storage.rs
modules/ingestor/src/service/format.rs
modules/ingestor/src/service/mod.rs
modules/ingestor/src/service/sbom/clearly_defined.rs
modules/ingestor/src/service/sbom/cyclonedx.rs
modules/ingestor/src/service/sbom/spdx.rs
test-context/src/lib.rs

I'm not entirely sure about the changes to `Format` in the last commit. We need further testing to see whether an additional byte array or the `SyncIoBridge` affects performance more adversely.

Have ingestion take bytes instead of stream and omit the Format arg

---

modules/fundamental/tests/sbom/spdx.rs

before
```console
➜  trustify git:(bit-faster-test) ✗ cargo nextest run ingest_spdx_medium
PASS [   5.922s] trustify-module-fundamental::fundamental sbom::spdx::perf::ingest_spdx_medium
PASS [  27.862s] trustify-module-fundamental::fundamental sbom::spdx::perf::ingest_spdx_medium_cpes
```
after
```console
➜  trustify git:(bit-faster-test) ✗ cargo nextest run ingest_spdx_medium
PASS [   4.746s] trustify-module-fundamental::fundamental sbom::spdx::perf::ingest_spdx_medium
PASS [  22.021s] trustify-module-fundamental::fundamental sbom::spdx::perf::ingest_spdx_medium_cpes
```
How I found it?
* opened a terminal and `cargo nextest run ingest_spdx_medium`
* opened other terminal and `ps -aux | rg fundamental` then grabbed the pid and then `flamegraph -o a.svg --pid pid_here`
then I saw 
then …

chore: makes the test a bit faster

---

modules/ingestor/src/service/advisory/csaf/loader.rs

This prevents the CSAF document being attached to the trace context. This definitely solved the IDE logs performance issue for me, but I guess it might have other benefits (memory usage) as well.

fix: prevent dumping the full CSAF document into the tracing context

---

Cargo.lock
Cargo.toml
entity/src/importer.rs
migration/src/lib.rs
migration/src/m0000570_add_import_progress.rs
modules/importer/src/endpoints.rs
modules/importer/src/model/mod.rs
modules/importer/src/runner/clearly_defined/walker.rs
modules/importer/src/runner/context.rs
modules/importer/src/runner/csaf/mod.rs
modules/importer/src/server/context.rs
modules/importer/src/server/mod.rs
modules/importer/src/server/progress.rs
modules/importer/src/service.rs
modules/importer/src/test.rs
modules/ingestor/src/service/sbom/clearly_defined.rs
openapi.yaml
xtask/src/dataset.rs

This extends the progress support to CSAF and SBOMs. It also persists the progress state in the database, and makes it available on the API.

feat: add progress support, backed by the database

---

modules/fundamental/benches/bench.rs
modules/fundamental/src/advisory/endpoints/mod.rs
modules/fundamental/src/sbom/endpoints/mod.rs
modules/fundamental/tests/sbom/reingest.rs
modules/importer/src/runner/clearly_defined/mod.rs
modules/importer/src/runner/csaf/storage.rs
modules/importer/src/runner/cve/mod.rs
modules/importer/src/runner/osv/mod.rs
modules/importer/src/runner/sbom/storage.rs
modules/ingestor/src/service/format.rs
modules/ingestor/src/service/mod.rs
modules/ingestor/src/service/sbom/clearly_defined.rs
modules/ingestor/src/service/sbom/cyclonedx.rs
modules/ingestor/src/service/sbom/spdx.rs
test-context/src/lib.rs

Fixes #715
We only auto-detect formats for the actix handlers providing our API.

fix: disable format detection for importers

---

Cargo.lock
Cargo.toml
RELEASE.md
openapi.yaml

Also, update the release documentation with changes for `cargo xtask`.

Prepare for next release

---

Cargo.lock
Cargo.toml
common/src/db/mod.rs
modules/fundamental/src/product/endpoints/mod.rs
modules/fundamental/tests/sbom/mod.rs
rust-toolchain.toml

Pre-req of https://github.com/trustification/trustify/issues/703
This also updates garage-door in order to work around https://github.com/trustification/trustify-ui/issues/145

build: update Rust to 1.80.1, update garage-door

---

xtask/src/dataset.rs

In case of an input file, the argument is ignored. So it shouldn't be silently accepted and discarded.

chore: fetch retries only sets this for the default config

---

.github/scripts/Containerfile
.gitignore

See https://github.com/trustification/trustify/issues/725
This fixes the issue of the missing dependencies. But still psql doesn't seem to run because it thinks it's been run as root.

build: add all required dependencies for embedded psql in the container

---

entity/src/sbom.rs
modules/fundamental/src/sbom/endpoints/test.rs
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/test.rs

Fixes #733
Added test to affirm that original SBOM can be downloaded by all hashes and uuid

fix: restore hashes in SBOM fetch api

---

modules/importer/src/runner/clearly_defined/mod.rs
modules/importer/src/runner/cve/mod.rs

fix: restore hard-coded base paths in CVE/ClearlyDefined walkers

---

modules/importer/src/service.rs

I hate having to scroll my importers to see an enabled one. I want to see the enabled ones at the top always.
Then after sorting them, I realized that the UI overrides my sort anyway. I wish it wouldn't. So with this, at least the api won't.

feat: sort importers by enabledness

---

.github/scripts/Containerfile.pmmode

Related to https://github.com/trustification/trustify/issues/725
```console
➜  trustify git:(minimal) ✗ podman run -it ff9a6186871e
RUST_LOG is unset, using default: 'info,actix_web_prom=error'
2024-09-05T20:12:41.391532Z  WARN trustd::db: Setting up managed DB; not suitable for production use!
2024-09-05T20:13:01.569275Z  INFO trustd::db: PostgreSQL installed in "/usr/local/bin/.trustify/postgres"
2024-09-05T20:13:01.569318Z  INFO trustd::db: Running on port 45587
2024-09-05T20:13:01.601705Z  INFO bootstrap: sqlx::postgres::notice: database "trustify" does not exist, skipping database=Database { username: "postgres", password: "trustify", host: "localhost", port: 45587, name: "trustify", max_conn: 75, min_conn: 25 }
2024-09-05T20:13:01.601756Z  INFO bootstrap: sqlx::query: summary="DROP …
```

fix: able to run pm-mode in container

---

Cargo.lock
Cargo.toml
modules/ingestor/src/service/advisory/cve/loader.rs

Many CVE project list v5 entries don't have a main title. However, most do have an English description. We already have the pattern of picking an English description as a primary piece of information, so why not re-use that pattern for a missing title too?
This PR lazily follows the pattern of picking the first `en` description, which we might improve on in the future. But for now, it seems good enough.
Aside from that, the PR also updates the `cpe` dependency to the most recent release, removing the need for the patch.
cc @carlosthe19916

Provide alternative CVE title, if none exists. And update one dep.

---

etc/test-data/osv/RSEC-2023-6.yaml
modules/ingestor/src/service/format.rs
modules/ingestor/tests/reingest/osv.rs
test-context/src/lib.rs

This not only requires processing of YAML files, but also detecting them with the Format enum.

fix: allow ingesting YAML based OSV

---

migration/src/lib.rs
migration/src/m0000600_remove_raise_notice_fns.rs
migration/src/m0000600_remove_raise_notice_fns/semver_cmp.sql

We were still getting 500 errors due to parallel execution of version/semver related pg functions ... this was due to usage of **RAISE NOTICE** which is not parallel safe.
For the pg curious ... the usage of **regexp_split_to_array**  can in some cases also not be parallel safe (though it is in our usage here).

fix parallel safe by removing raise notice

---

modules/ingestor/src/service/mod.rs

**result.id** strings out to a uuid prefixed with "urn:uuid" ... which when analysis service is invoked in ingestor results in 2 entries in graph hashmap of the same graph (e.g one with a key of normal hypenated uuid and the other with a urn:uuid prefix. That is because lazy loading uses just the unadorned uuid string ... so eventually between using REST API search (lazy loading) and ingestor we end up with two different entries in the hashmap of the same sbom -  that was silly/wrong.
The fix chops off the urn:uuid bit from the string and its ugly - open to any better suggestions.

Fix graph hashmap key mangling on analysis service invoke

---

Cargo.lock
modules/fundamental/Cargo.toml
modules/fundamental/src/advisory/endpoints/mod.rs
modules/fundamental/tests/dataset.rs
modules/ingestor/src/service/dataset/mod.rs
modules/ingestor/src/service/mod.rs
modules/storage/src/service/fs.rs
test-context/src/lib.rs

Ingesting a dataset did not store the source document, of the ingested documents, in storage backend. This change fixes this.

fix: store documents when ingesting a dataset

---

migration/src/lib.rs
migration/src/m0000610_improve_version_cmp_fns.rs
migration/src/m0000610_improve_version_cmp_fns/mavenver_cmp.sql
migration/src/m0000610_improve_version_cmp_fns/semver_cmp.sql
migration/tests/mavenver.rs
migration/tests/semver.rs
migration/tests/version_common.rs
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/vulnerability/service/test.rs
modules/graphql/src/test.rs

Add tests to see if maven/semver version_matches is right or not.

---

.github/workflows/openapi.yaml

- For each change done to the file openapi.yaml file there will be a new PR against the trustify-ui repository to copy the content of the openapi.yaml file
- The ui repository has a hard dependency to the openapi yaml file and currently is way behind the latest changes, this PR should help the ui guys to realize there are changes to introduce and apply any remediation if needed.
Tested in my own forked branch and:
- This is how it looks a PR created by the gh action introduced in this PR https://github.com/trustification/trustify-ui/pull/159
- This is the action build log https://github.com/carlosthe19916/trustify/actions/runs/10910107238
- I added a `GH_PAT` secret to this repository in case this PR is accepted and merged

ci: synchronize openapi.yaml on trustify-ui

---

.github/workflows/openapi.yaml

Solves https://github.com/trustification/trustify/issues/820
The synch action for the openapi yaml file will only be triggered on the trustification/trustify repository and not on forks

execute openapi.yaml synch with ui only on trustification and not on forks

---

modules/ingestor/src/graph/purl/creator.rs

mitigates the likelihood of deadlocks when creating purls by enforcing order creating the base, versioned and qualified purl entities, fixes #817.
**Note** - [refactoring](https://github.com/trustification/trustify/issues/771) of purl (for performance) will fully address this.

Mitigate deadlocks when creating purls

---

migration/src/lib.rs
migration/src/m0000620_parallel_unsafe_pg_fns.rs
migration/src/m0000620_parallel_unsafe_pg_fns/gitver_version_matches.sql
migration/src/m0000620_parallel_unsafe_pg_fns/is_numeric.sql
migration/src/m0000620_parallel_unsafe_pg_fns/maven_version_matches.sql
migration/src/m0000620_parallel_unsafe_pg_fns/mavenver_cmp.sql
migration/src/m0000620_parallel_unsafe_pg_fns/rpmver_cmp.sql
migration/src/m0000620_parallel_unsafe_pg_fns/rpmver_version_matches.sql
migration/src/m0000620_parallel_unsafe_pg_fns/semver_cmp.sql
migration/src/m0000620_parallel_unsafe_pg_fns/semver_eq.sql
migration/src/m0000620_parallel_unsafe_pg_fns/semver_gt.sql
migration/src/m0000620_parallel_unsafe_pg_fns/semver_gte.sql
migration/src/m0000620_parallel_unsafe_pg_fns/semver_lt.sql
migration/src/m0000620_parallel_unsafe_pg_fns/semver_lte.sql
migration/src/m0000620_parallel_unsafe_pg_fns/semver_version_matches.sql
migration/src/m0000620_parallel_unsafe_pg_fns/version_matches.sql

mitigates #824 #829 - once purl refactor beds in we may reverse this decision.

mark version_matches pg funcs as unsafe.

---

.gitignore
Cargo.lock
Cargo.toml
modules/fundamental/Cargo.toml
modules/fundamental/src/ai/endpoints/mod.rs
modules/fundamental/src/ai/endpoints/test.rs
modules/fundamental/src/ai/mod.rs
modules/fundamental/src/ai/model/mod.rs
modules/fundamental/src/ai/service/mod.rs
modules/fundamental/src/ai/service/prefix.txt
modules/fundamental/src/ai/service/test.rs
modules/fundamental/src/ai/service/tools.rs
modules/fundamental/src/endpoints.rs
modules/fundamental/src/error.rs
modules/fundamental/src/lib.rs
modules/fundamental/src/openapi.rs
openapi.yaml
xtask/Cargo.toml
xtask/src/ai.rs
xtask/src/main.rs

Add a `cargo xtask ai` cli interface to the AI service 
It uses that langchanin-rust apis interface with an LLM of your choice.
To run it against an OpenAI compatible endpoint, configure and export the following env variables:
* OPENAI_API_KEY
* OPENAI_API_BASE
* OPENAI_MODEL
To run against OpenAI, just set the 'OPENAI_API_KEY' env var.
Use ollama.com to run it all locally:
* install https://ollama.com/
* `ollama pull llama3.1:70b`
* `OPENAI_API_KEY=ollama OPENAI_API_BASE=http://localhost:11434/v1 OPENAI_MODEL=llama3.1:70b cargo xtask ai`

Add AI endpoint under: `/api/v1/ai/completions` to query the DB for information.

---

.github/workflows/container-latest.yaml
.github/workflows/rita-pr-merged.yaml

There are some workflows we want to run in downstream forks, and others we don't.

fix: avoid workflow failures in forks

---

.github/workflows/openapi.yaml

The last execution of the openapi gh action failed due to recent changes. This PR should fix it. Here is this PR running in my local fork to prove it won't fail if this PR is merged https://github.com/carlosthe19916/trustify/actions/runs/11131756934/job/30934066364
Also taking the chance to replace `npm install` by `npm ci` to guarantee the package.lock will be respected

fix: openapi.yaml github action execution

---

common/src/db/query.rs
modules/fundamental/src/purl/endpoints/test.rs

I'm not sure how this worked, frankly. Maybe actix request handlers somehow do The Right Thing with unbalanced '=' operators?

Query params should be url-encoded

---

.github/workflows/build-binary.yaml

As warned by GitHub:
>  A brownout will take place on November 4, 14:00 UTC - November 5, 00:00 UTC to raise awareness of the upcoming macOS-12 environment removal. For more details, see https://github.com/actions/runner-images/issues/10721

ci: update deprecated github runner

---

.github/workflows/container-latest.yaml
.github/workflows/latest-release.yaml

Fixes: #804
Requires an `OPENSHIFT_TOKEN` secret that enables privileged access to an OCP instance, e.g. https://api.cluster.trustification.rocks:6443
The following commands were used to generate the token on the OCP host:
```
oc create serviceaccount ${ACCT_NAME}
oc create clusterrolebinding ${ACCT_NAME} --clusterrole=cluster-admin --serviceaccount=default:${ACCT_NAME}
oc create token ${ACCT_NAME} --duration=$((365*24))h
```
Upon successful completion of the `latest-release` workflow, the app will be available here:
https://trustify-latest-staging.apps.cluster.trustification.rocks/

feat: CI pipeline to build, package, test, and deploy each merged PR

---

common/src/db/query.rs
modules/analysis/src/endpoints.rs
modules/analysis/src/service.rs

Enhances query.rs to be able to perform comparisons with **Uuid** when supplied via inline query params.
Enabling the analysis graph (api/v1/analysis) to filter on **sbom_id**, **node_id** and exact **name**.
```
api/v1/analysis/root-component?q=name=A&node_id=SPDXRef-A&sbom_id=urn:uuid:019289ff-232c-7780-b0d5-22b6e5dc4be5
```
where we retain **contains** style search with:
```
api/v1/analysis/root-component?q=libcurl
```
to filter exact match use:
```
api/v1/analysis/root-component?q=name=libcurl
```
and similar for dep endpoints eg.
```
api/v1/analysis/dep?q=name=A&node_id=SPDXRef-A&sbom_id=urn:uuid:019289ff-232c-7780-b0d5-22b6e5dc4be5
api/v1/analysis/dep?q=libcurl
api/v1/analysis/dep?q=name=libcurl
```
**Note** - In real usage - the above inline _query name=values&name=value_ should …

Enhance query filters to handle Uuid and enable analysis graph to use filters.

---

.github/scripts/benchmark.sh
.github/workflows/benchmark.yaml
etc/datasets/Makefile

This adds an benchmark test for ingesting dataset 3: https://github.com/trustification/trustify/tree/main/etc/datasets/ds3
It will measure, record, and compare performance over time on the main branch, and alert on PRs. There's a also a published version of the data, which can be previewed on my personal fork: https://ctron.github.io/trustify/dev/bench/
Right now, there is only a single test. Which doesn't use any specific benchmark tool. However, we can extend this, using `cargo bench` or `criterion-rs` in the future.

ci: ds3 ingestion benchmark

---

common/src/db/query.rs

Relates to #934
We resolve dates or times relative to the missing complement in the field's `OffsetDateTime` value, essentially allowing one to easily filter on naive dates and times.
We also enable the LIKE operator for Dates, such that `published~2021` would work, for example.

Flesh out the eq/ord impls for dates more intuitively

---

etc/test-data/cyclonedx/cyclonedx-circular.json
etc/test-data/cyclonedx/loop.json
etc/test-data/cyclonedx/simple.json
etc/test-data/cyclonedx/simple_with_purl_dep_ref.json
modules/analysis/src/service.rs

We need to ensure (when similarly encoded) that ingestion of cyclonedx matches spdx ingestion. 
We also should take care to avoid any race conditions if we encounter sbom that encode circular dependencies.

chore: Enhance testing around cyclonedx ingestion

---

Cargo.lock
modules/storage/Cargo.toml
modules/storage/src/service/compression/mod.rs
modules/storage/src/service/fs.rs
modules/storage/src/service/mod.rs
modules/storage/src/service/s3.rs
modules/storage/src/service/temp.rs
server/src/lib.rs

feat: enable compression of docs stored on S3

---

Cargo.toml

Fixes #894
Took me too long to figure out that we need to [enable a sea_orm feature](https://www.sea-ql.org/SeaORM/docs/install-and-config/debug-log/). Once done, you can see sea_orm statements in tests after setting the `RUST_LOG` env var:
`RUST_LOG=sea_orm=debug`
Or more specifically,
`RUST_LOG=none,sea_orm::driver::sqlx_postgres=debug`

Enable sea_orm's debug logging

---

Cargo.lock
Cargo.toml
modules/fundamental/src/advisory/service/test.rs
modules/fundamental/src/ai/endpoints/expected_tools_result.json
modules/fundamental/src/ai/endpoints/test.rs
modules/fundamental/src/ai/service/mod.rs
modules/fundamental/src/ai/service/prefix.txt
modules/fundamental/src/ai/service/test.rs
modules/fundamental/src/ai/service/tools/advisory_info.rs
modules/fundamental/src/ai/service/tools/cve_info.rs
modules/fundamental/src/ai/service/tools/logger.rs
modules/fundamental/src/ai/service/tools/mod.rs
modules/fundamental/src/ai/service/tools/package_info.rs
modules/fundamental/src/ai/service/tools/product_info.rs
modules/fundamental/src/ai/service/tools/sbom_info.rs
modules/fundamental/src/sbom/service/test.rs

* Move more of the resource info out of the system messages/prefix into the Tools descriptions
* Disable the product-info tool for now, it’s better to use the sbom-info for similar information.
* Bump async-openai version
* switch to new langchain-rust patch branch
* Add more info to tool response.

chore(ai): endpoint improvements.

---

common/src/hashing.rs
entity/src/lib.rs
entity/src/sbom.rs
entity/src/source_document.rs
migration/src/lib.rs
migration/src/m0000690_alter_sbom_details.rs
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/source_document/model/mod.rs
modules/graphql/src/sbom.rs
modules/ingestor/src/graph/advisory/mod.rs
modules/ingestor/src/graph/sbom/clearly_defined.rs
modules/ingestor/src/graph/sbom/cyclonedx.rs
modules/ingestor/src/graph/sbom/mod.rs
modules/ingestor/src/graph/sbom/spdx.rs
modules/ingestor/src/service/sbom/clearly_defined.rs
openapi.yaml

Add `data_licenses` and `size` to SBOMs.
And yes, it's 0 to n licenses. As that's the reality of the data. I assume that in most cases it is 0 or 1, but with CycloneDX it can be more than one.
Closes #949

feat: add size of documents and sbom data license

---

common/src/db/query.rs
common/src/db/query/columns.rs
common/src/db/query/filter.rs
common/src/db/query/sort.rs

We enhance the Filter and Sort structs to deal with more complex LHS expressions, e.g. `"table.column"->>'key'`, instead of just column names.
Specifically, this enables the querying of `JsonBinary` and `Json` columns.

Refactor query logic to support querying of nested structures

---

entity/src/importer.rs
migration/src/lib.rs
migration/src/m0000730_alter_importer_add_progress.rs
modules/importer/src/model/mod.rs
modules/importer/src/runner/common/walker/git.rs
modules/importer/src/runner/progress.rs
modules/importer/src/server/context.rs
modules/importer/src/server/progress.rs
modules/importer/src/service.rs
modules/importer/src/test.rs
openapi.yaml

If we can find a previous commit, we reset and create a fresh clone of the repository.
This can happen if there was a force push to the original repository.

fix: re-walk all files if the commit cannot be found

---

Cargo.lock
Cargo.toml
etc/test-data/osv/PYSEC-2024-55.yaml
modules/fundamental/tests/advisory/osv/ingest.rs
modules/fundamental/tests/advisory/osv/mod.rs
modules/ingestor/src/service/advisory/osv/loader.rs

The spec says it's optional. So let's make it optional.
Closes https://github.com/trustification/trustify/issues/990

fix(osv): treat `published` as optional

---

Cargo.lock
entity/src/cpe.rs
entity/src/product.rs
entity/src/product_status.rs
migration/src/lib.rs
migration/src/m0000641_update_product_status.rs
modules/fundamental/Cargo.toml
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/vulnerability/model/details/vulnerability_advisory.rs
modules/fundamental/src/vulnerability/service/test.rs
modules/ingestor/src/service/advisory/csaf/creator.rs
modules/ingestor/src/service/advisory/csaf/product_status.rs

This PR should be able to correlate VEX advisories from CSAF files that don't have product identifier helpers (purls) to correct sboms.
To test it, run a local instance of trustify
Ingest one of the [datasets](https://github.com/trustification/trustify/blob/main/etc/datasets/README.md) (ds1 and ds3 should both work)
`http POST localhost:8080/api/v1/dataset @etc/datasets/ds3.zip`
And inspect results for some of the documents, e.g. CVE-2023-0044 and quarkus-sbom
`http GET localhost:8080/api/v1/vulnerability/CVE-2023-0044 | jq .advisories`
(find uuid of quarkus-sbom and the provide it below)
`http GET http://localhost:8080/api/v1/sbom/urn%3Auuid%3A01931b9e-8c5f-7681-8343-c8265a1257f1/advisory
`
This PR doesn't link found components to actual SBOM purls. That will be done in a separate …

feat: csaf correlation - correlate vulnerability to purls and sboms

---

.github/workflows/ci-ai.yaml

Adding a CI workflow dedicated to the AI code to be executed only when and if changes are done to the AI module, i.e. within `modules/fundamental/src/ai/`, to avoid slowing down the "main" [`ci`](https://github.com/trustification/trustify/blob/main/.github/workflows/ci.yaml) job with unnecessary AI tests.
Obviously I'm happy to remove the path filter if these tests are considered worth being executed for every PR, independently from the changes in the PR itself.

chore: add 'ci-ai' job

---

.github/workflows/ci-ai.yaml
Cargo.lock
modules/fundamental/Cargo.toml
modules/fundamental/src/ai/endpoints/test.rs
modules/fundamental/src/ai/service/test.rs

In https://github.com/trustification/trustify/pull/919 the `product-info` tool has been commented in favor of the `sbom-info` one and in this PR the tests, previously targeting the `product-info` tool, have been refactored to the `sbom-info` one.

chore: AI Add 'sbom-info' tool test

---

etc/test-data/spdx/simple.json
modules/analysis/src/endpoints.rs
modules/analysis/src/model.rs
modules/analysis/src/service.rs
openapi.yaml

This PR contains a few interconnected changes to analysis graph:
* add **version** to node
* enable filtering with **version**
* ensure we handle circular dependencies (ex. _etc/test-data/spdx-ubi-examples/v2.json_)
*  heavy refactoring of graph routines
Additionally we should no longer extract name from the component **pURL** - as often a component will  not have a pURL ! - so we retrieve from **sbom_node**. 
**Note**:  We can further refactor in retrieve_ fns but left that till whenever we contemplate doing a MRU style forest of graphs.

Add version and handle circular deps in analysis graphs

---

migration/src/lib.rs
migration/src/m0000740_ensure_get_purl_fns.rs
migration/src/m0000740_ensure_get_purl_fns/get_purl.sql
modules/analysis/src/model.rs
modules/analysis/src/service.rs
openapi.yaml

Missed off a commit for analysis graph (which adds relationship and fixes deps circularity)... also we need to perform data migration to ensure **get_purl** psql function serialises to correct **pURL** format (which is used by analysis graph). 
While in the area, optimised the **get_purl** fn for performance.

Fix circular deps in analysis graph and add purl migration for get_purl psql func

---

modules/storage/src/config.rs
modules/storage/src/service/compression/mod.rs

I confirmed that both compressed and uncompressed files rendered correctly when downloaded via the trustify app using [this bucket](https://us-east-1.console.aws.amazon.com/s3/buckets/trustify-jcrossley?region=us-east-1)

fix: s3 storage config options and encoding case insensitivity

---

Cargo.lock
entity/src/relationship.rs
modules/analysis/Cargo.toml
modules/analysis/src/endpoints.rs
modules/analysis/src/model.rs
modules/analysis/src/service.rs
openapi.yaml

SPDX/cyclonedx both allow defining components without any explicit relationship.
In our internal logical database we consider existence of a component, in an SBOM to have an implied **Undefined** relationship with the **DESCRIBES** component. 
This PR ensures we do the similar in analysis graph.
Example;
Where **quarkus-vertx-http** component has no defined relationship (in _etc/test-data/spdx/quarkus-bom-3.2.11.Final-redhat-00001.json_)
```
>curl -H "Authorization:$(oidc token testing-client --bearer)" "http://localhost:8080/api/v1/analysis/root-component/quarkus-vertx-http"  | jq | bat --language=json
```
Previously this would list no ancestor component as no explicit dependency was defined in the SBOM thus no relationship was set in analysis graph.
```
{
"sbom_id": …
```

Set implied relationships for SBOM components in analysis graph

---

modules/fundamental/src/ai/endpoints/test.rs
modules/fundamental/src/purl/endpoints/test.rs
modules/fundamental/src/sbom/endpoints/test.rs
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/sbom/service/test.rs
modules/fundamental/src/vulnerability/endpoints/test.rs
modules/fundamental/src/vulnerability/service/test.rs
openapi.yaml

Fixes #1006 by making the sbom #packages available in `/api/v1/vulnerability/{id}` as well as `/api/v1/sbom/{id}`

fix: move number_of_packages to SbomHead

---

cvss/src/cvss3/score.rs
entity/src/cvss3.rs
modules/fundamental/src/advisory/model/details/advisory_vulnerability.rs
modules/fundamental/src/ai/service/tools/sbom_info.rs
modules/fundamental/src/sbom/endpoints/test.rs
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/vulnerability/model/details/mod.rs
modules/fundamental/src/vulnerability/model/details/vulnerability_advisory.rs
modules/fundamental/src/vulnerability/model/mod.rs
modules/fundamental/src/vulnerability/service/test.rs
modules/fundamental/tests/advisory/csaf/delete.rs
modules/fundamental/tests/advisory/csaf/reingest.rs
modules/fundamental/tests/advisory/osv/reingest.rs
modules/graphql/src/sbomstatus.rs
openapi.yaml

feat: provide scores in sbom details response

---

modules/analysis/src/service.rs

Add **retrieve_all_sbom_roots_by_name** function that searches for a component(s) by name in a specific sbom, then returns that components root component.
Can be used thusly:
```
let roots = service
.retrieve_all_sbom_roots_by_name(sbom_id, component_name, ())
.await?;
```
Intended for use in #1014
**Note** - most of graph is based on string values ... this was an explicit design decision I do with graph stuff up front, its likely at some point I will revert these values back to some normal types at some point (ex. sbom_id would be stored in graph as a Uuid).

Add retrieve_all_sbom_roots_by_name() func

---

.github/workflows/build-binary.yaml

The reason for this, that we enable sqlx's TLS mode. Which requires, openssl, even for the build-dependency. In combination with musl, this creates some major problems, as vendoring doesn't seem to work.
For now, we just disable musl.

ci: disable musl builds for now

---

etc/test-data/cyclonedx/simple_cpe.json
etc/test-data/cyclonedx/simple_cpe_2.json
etc/test-data/cyclonedx/simple_cpe_3.json
modules/fundamental/tests/sbom/cyclonedx/cpe.rs
modules/fundamental/tests/sbom/cyclonedx/mod.rs
modules/ingestor/src/graph/sbom/cyclonedx.rs
test-context/src/lib.rs

In cases where the metadata component doesn't have an explicit `bom-ref`, we now create an artificial one, so that the relationship gets created.
CycloneDX doesn't need such a reference for the relationship, but we do. So instead of ignoring the information, we create an artificial value. Just like primary IDs in the database.
Also, improve some test coverage.

fix: always create "described by" relationships

---

entity/src/advisory.rs
migration/src/lib.rs
migration/src/m0000750_alter_advisory_add_document_id.rs
modules/fundamental/src/advisory/endpoints/test.rs
modules/fundamental/src/advisory/model/mod.rs
modules/fundamental/src/advisory/service/test.rs
modules/fundamental/src/ai/service/tools/advisory_info.rs
modules/fundamental/src/organization/endpoints/test.rs
modules/fundamental/src/organization/service/test.rs
modules/fundamental/src/vulnerability/endpoints/test.rs
modules/graphql/src/advisory.rs
modules/ingestor/src/graph/advisory/mod.rs
modules/ingestor/src/service/advisory/csaf/loader.rs
modules/ingestor/src/service/advisory/cve/loader.rs
modules/ingestor/src/service/advisory/osv/loader.rs
modules/ingestor/tests/db.rs
openapi.yaml

Fix an issue for the UI, where the document ID was reported as `https://www.redhat.com/#CVE-2023-0044` for CSAF documents. However, in v1 the ID was `CVE-2023-0044`.
This is due to the fact that we have a list of IDs for each advisory: an internal DB one (`id`), one that uniquely identifies the docment (`identifier`), and now one which carries the ID as reported by the document (`document_id`). The latter one should be show in the UI.
@carlosthe19916 This also means that at the UI needs to pick up the new field, once this PR is merged.

chore: add a document id for advisories

---

migration/src/lib.rs
migration/src/m0000760_product_status_index.rs
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/vulnerability/service/test.rs

This is db implementation of feature needed for #994.
I would go with it to unlock work on UI (#1043) and see if and how to replace same functionality with graph in the future.
I'm keeping #1014 draft PR as a placeholder for this future work

feat: find purls for affected packages

---

common/auth/src/authorizer/mod.rs
common/src/db/query/columns.rs
common/src/db/query/filter.rs
modules/fundamental/src/ai/service/tools/package_info.rs
modules/fundamental/src/purl/endpoints/test.rs
modules/fundamental/src/purl/service/mod.rs
modules/fundamental/src/purl/service/test.rs

Fixes #888
Fixes #951
Fixes #972
This introduces some potential naming conflicts, specifically that `type` is a valid PURL _qualifier_ as well as an attribute of the PURL itself, therefore we currently alias `ty` to `type`, which effectively prohibits using the `type` _qualifier_ in queries; only the type of the PURL itself may be used.
We need to decide which qualifiers we want to support.

fix: enable filtering/sorting on qualified purl json fields

---

Cargo.lock
README.md
etc/deploy/compose/compose.yaml
modules/fundamental/src/error.rs
modules/storage/Cargo.toml
modules/storage/src/service/fs.rs
modules/storage/src/service/s3.rs

Also: add instrumentation to `store` and align DB passwords.

fix: report 500 in case of storage errors, align with other errors

---

migration/src/lib.rs
migration/src/m0000800_alter_product_version_range_scheme.rs
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/vulnerability/service/test.rs
modules/ingestor/src/service/advisory/csaf/product_status.rs

This PR contains rework of sbom to vulnerability use case. The performance should be now much better and it should fix some issues with the results in the process as well. I tested it manually with some larger sboms on top of DS1, like rhel-7 and everything works much smoother now.
There's still room for other performance improvements, but let's do that in follow-up PRs

fix: improve sbom to vunerabilities correlation

---

modules/ingestor/src/graph/product/mod.rs
modules/ingestor/src/service/advisory/csaf/creator.rs

This PR improves ingestion performance of CSAF documents, by doing batch insert for products and version ranges.
Performance improvements are significant for a large csaf documents
Before:
```
$ time csaf scoop http://localhost:8080/api/v1/advisory etc/datasets/ds3/csaf/2023/cve-2023-44487.json
________________________________________________________
Executed in  210.75 secs      fish           external
usr time    4.01 millis    0.07 millis    3.94 millis
sys time   24.75 millis    1.27 millis   23.49 millis
```
After:
```
$ time csaf scoop http://localhost:8080/api/v1/advisory etc/datasets/ds3/csaf/2023/cve-2023-44487.json
________________________________________________________
Executed in   53.29 secs      fish           external
usr time    5.26 millis    0.09 millis    5.17 millis …
```

fix: optimize import of product related entities during csaf ingestion

---

entity/src/version_scheme.rs
modules/ingestor/src/graph/advisory/advisory_vulnerability.rs
modules/ingestor/src/graph/product/mod.rs
modules/ingestor/src/service/advisory/csaf/creator.rs
modules/ingestor/src/service/advisory/csaf/loader.rs

This PR handles two things. 
First it removes select in loop that checks for preexisting purl statuses. Instead I added a bit of logic to return early from ingesting already ingested csaf document, which I believe is the case this was protecting from.
Additionally, now product related entities use predictable ids that was missing in yesterdays batch insert PR. There are still some workarounds in this area that will be tackled next, when the sam work is done for ingesting SBOMs.
This all result in further speedup of csaf ingestion, where `cve-2023-44487` goes locally from 50 to 20 sec.
The whole dataset 3 now ingests for 30 sec
```
time http POST localhost:8080/api/v1/dataset @etc/datasets/ds3.zip
________________________________________________________
Executed in   35.23 secs      fish …
```

fix: use predictable ids for product related entities and additionally speed up csaf ingestion

---

modules/fundamental/src/purl/endpoints/test.rs
modules/fundamental/src/purl/model/details/purl.rs
modules/fundamental/tests/advisory/csaf/delete.rs
modules/fundamental/tests/advisory/csaf/reingest.rs
modules/fundamental/tests/advisory/osv/reingest.rs
openapi.yaml

feat: add average_severity to PurlStatus

---

modules/analysis/src/endpoints.rs
modules/analysis/src/test.rs
modules/fundamental/src/test/common.rs
modules/ingestor/tests/common.rs
test-context/src/call.rs

We have 3 places that are essentially doing the same thing. That thing is more correctly done in a single place and test context seemed the most appropriate.

refactor: dry up redundant test app creation logic

---

etc/test-data/cyclonedx/openssl-3.0.7-18.el9_2.cdx_1.6.sbom.json
modules/analysis/src/endpoints.rs
modules/ingestor/src/graph/sbom/cyclonedx.rs

Relates to #1131
I'm not entirely sure my right and left is correct, because I don't fully grok the expected output of `analysis/root-component` and `analysis/dep`.

feat: create GeneratedFrom relationship from CycloneDX dependencies

---

server/src/sample_data.rs

This adds two example entries for GHSA data in the OSV format. One full, and one starting with 2024 data.

feat: add two example entries fro GHSA data

---

migration/src/lib.rs
migration/src/m0000830_perf_indexes.rs
modules/fundamental/src/ai/service/tools/sbom_info.rs
modules/fundamental/src/purl/service/test.rs
modules/fundamental/src/sbom/endpoints/mod.rs
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/sbom/service/sbom.rs
modules/fundamental/src/sbom/service/test.rs
modules/fundamental/src/vulnerability/service/test.rs
modules/fundamental/tests/sbom/reingest.rs
modules/graphql/src/sbomstatus.rs

Most visibly (and easy to adhoc test) this resolves list of vulns faster on http://localhost:8080/sboms listing and  http://localhost:8080/vulnerabilities.
Also various speed improvements in various places.
Addresses both #1018 and  #1140.

chore: perf improvements

---

entity/src/relationship.rs
modules/fundamental/src/purl/endpoints/test.rs
modules/fundamental/src/purl/model/details/purl.rs
openapi.yaml

Fixes #1131
This might take care of other camp/atlas issues, too, since any relationships associated with the purl (not just `generated_from`) will be included.

feat: show relationships in response from /api/v1/purl/{key}

---

modules/fundamental/src/ai/endpoints/mod.rs
modules/fundamental/src/ai/endpoints/test.rs
modules/fundamental/src/ai/model/mod.rs
modules/fundamental/src/ai/service/mod.rs
modules/fundamental/src/ai/service/test.rs
openapi.yaml
xtask/src/ai.rs

LLM internal state messages is simplified to be a single field either on ChatState or in the Conversation table. We now keep timestamps for individual ChatMessages.
Also drop the db connection arg from the completions method as the DB is Not needed for those calls.
You can test out the completions API using the UI at: https://github.com/chirino/ai-assistant-vite
just `npm i && npm run dev` and use the browser link outputted.

feat[ai]: Add conversation endpoints.

---

.github/workflows/ci.yaml

An example of a job that failed can be found at:
https://github.com/trustification/trustify/actions/runs/12791739126/job/35660536423

Cache the Theseus postgresql install to avoid rate limit errors on CI PR jobs.

---

Cargo.lock

This PR points to the latest version available of the UI, the one that contains the /v2/ changes done after https://github.com/trustification/trustify/pull/1133

fix: Point to a UI that uses /v2/ prefixes

---

etc/deploy/compose/compose.yaml
migration/src/m0000800_alter_product_version_range_scheme.rs
migration/src/m0000800_alter_product_version_range_scheme/migration_down.sql
migration/src/m0000800_alter_product_version_range_scheme/migration_up.sql

This PR contains improved migration query mentioned in #1142 
Query by itself runs for about ~30 min on load test database dump, but I didn't get to test the migration because of https://github.com/trustification/trustify-load-test-runs/issues/5

fix: improve product version range migration

---

modules/fundamental/tests/dataset.rs
modules/ingestor/src/service/advisory/osv/loader.rs

Enhanced OSV loader to manage the (range)`type` and `ecosystem` properly when dealing with the `version_range.version_scheme_id` value.
In this way the GHSA advisories in `ds3` correlate with the `quarkus-bom` and in this regard a test has been added.

OSV loader: set properly VersionScheme in version_range

---

etc/test-data/spdx/openssl-3.0.7-18.el9_2.spdx.json
modules/analysis/src/endpoints.rs

See https://issues.redhat.com/browse/TC-2051
This doesn't include the request to show relationships in the response of `/api/v2/purl` as there's a pending request to remove that requirement.

Add unit test affirming TC-2051

---

etc/test-data/indigestable.json
modules/ingestor/src/service/format.rs

At present, only our test fixtures call `Format::from_bytes` and we obviously don't currently pass invalid docs to our tests. But if we expose this behavior to users, we'll want to prevent infinite loops attempting to ingest invalid docs of an unknown format.

fix: infinite loop when invalid file passed to Format::from_bytes

---

migration/src/m0000720_alter_sbom_fix_null_array.rs
migration/src/m0000720_alter_sbom_fix_null_array/migration_up.sql

This is a fix for https://github.com/trustification/trustify-load-test-runs/issues/5
The fix is to use `USING COALESCE` to update NULL values before set the constraint. As I couldn't find an easy way to do that in sea-orm, I converted the migration to raw sql

fix: sbom license migration to update nulls

---

modules/analysis/src/error.rs

Right now, it is being reported as an internal server error.

fix: report CPE parsing as "bad request"

---

modules/analysis/src/endpoints/test.rs
test-context/src/lib.rs
test-context/src/subset.rs

Verify the relationship type shows up in 
`/api/v2/analysis/root-component` API calls.
Part of issue #1140

Add tests for spdx "relationshipType": "PACKAGE_OF"

---

docs/adrs/00002-analysis-graph.md

Rendered version: https://github.com/trustification/trustify/blob/adr-analysis-conceptual/docs/adrs/00002-analysis-graph.md

adr for conceptual view

---

modules/analysis/src/endpoints/test.rs
test-context/src/subset.rs

Removed the non-recursive subset fn as it wasn't being used anywhere. There may yet be a need to introduce some mechanism that ensures json array values are matched exactly, rather than the current "contained" match.

Simplified relationship tests a bit

---

modules/analysis/src/endpoints/test.rs

Makes it easier to further constrain the results without assuming any particular order in the output.

More test cleanup; removing hardcoded array indexing

---

common/infrastructure/Cargo.toml
common/infrastructure/src/app/http.rs
common/infrastructure/src/app/mod.rs
common/infrastructure/src/infra.rs
common/infrastructure/src/lib.rs
common/infrastructure/src/otel.rs
docs/design/log_tracing.md
docs/otel.md
etc/telemetry/compose.yaml
etc/telemetry/config.yaml
etc/telemetry/prometheus.yaml
server/src/profile/api.rs
server/src/profile/importer.rs
trustd/src/db.rs

* Adds prometheus to existing compose file
* Avoids conflicts with current custom metrics configs
* Moved otel dev docs to docs/otel.md
* Renamed tracing.rs to otel.rs as now it contains metrics [signal](https://opentelemetry.io/docs/concepts/signals/)

feat: Gathering metrics at development time

---

.github/workflows/benchmark.yaml

This seems to fail PR ci checks consistently.

Don’t benchmark on every PR.  

---

.cargo/config.toml
.github/workflows/ci.yaml
common/Cargo.toml
common/src/db/mod.rs
migration/Cargo.toml
migration/src/ai.rs
migration/src/lib.rs
migration/tests/tests.rs
modules/fundamental/Cargo.toml
modules/fundamental/src/ai/endpoints/mod.rs
modules/fundamental/src/ai/endpoints/test.rs
modules/fundamental/src/endpoints.rs
modules/fundamental/src/lib.rs
openapi.yaml
server/Cargo.toml
trustd/Cargo.toml
xtask/Cargo.toml
xtask/src/main.rs

fix: add an ai feature so that ai features are not compiled by default.

---

migration/src/lib.rs
migration/src/m0000870_source_doc_indexes.rs
modules/analysis/src/service/test.rs
modules/fundamental/src/advisory/service/test.rs
modules/fundamental/tests/sbom/cyclonedx/mod.rs
modules/fundamental/tests/sbom/cyclonedx/reingest.rs
modules/fundamental/tests/sbom/mod.rs
modules/ingestor/src/graph/advisory/mod.rs
modules/ingestor/src/graph/mod.rs
modules/ingestor/src/graph/sbom/mod.rs
modules/ingestor/src/service/advisory/csaf/loader.rs
modules/ingestor/src/service/advisory/cve/loader.rs
modules/ingestor/src/service/advisory/osv/loader.rs
modules/ingestor/src/service/mod.rs
modules/ingestor/src/service/sbom/clearly_defined.rs
modules/ingestor/src/service/sbom/clearly_defined_curation.rs
modules/ingestor/src/service/sbom/cyclonedx.rs
modules/ingestor/src/service/sbom/spdx.rs

Also: 
* Re-add indices for digest columns on the source document table
* Reduce logging of happy path during ingestion, has a performance impact
* Honor the existence of other documents too, although that didn't cause any issues so far
Closes: #1236, #303

Fix issue with duplicate CDX nodes

---

Cargo.lock
Cargo.toml
common/Cargo.toml
common/src/cpe.rs
common/src/purl.rs
docs/env-vars.md
entity/Cargo.toml
entity/src/relationship.rs
modules/analysis/Cargo.toml
modules/analysis/src/config.rs
modules/analysis/src/endpoints/mod.rs
modules/analysis/src/lib.rs
modules/analysis/src/model.rs
modules/analysis/src/service/load.rs
modules/analysis/src/service/mod.rs
modules/analysis/src/service/render/mod.rs
modules/analysis/src/service/test.rs
modules/analysis/src/service/walk.rs
modules/analysis/src/test.rs
modules/fundamental/src/test/common.rs
modules/fundamental/tests/sbom/spdx/aliases.rs
modules/ingestor/tests/common.rs
server/src/openapi.rs
server/src/profile/api.rs
xtask/src/precommit.rs

Fixes issue https://github.com/trustification/trustify/issues/1218

Replace GraphMap’s map with a moka::sync::Cache

---

migration/src/lib.rs
migration/src/m0000880_org_name_index.rs

A primary way of finding Organizations is "by name". I think we should have an index for that.

fix: add index for organizations by name

---

Cargo.lock
Cargo.toml
RELEASE.md

The branch release/0.2.z should point to the ui dependency also using the release/0.2.z branches

[release/0.2.z] task: align trustify-ui dependency branches

---

RELEASE.md

Based on https://github.com/trustification/trustify/pull/1249
Aligned the RELEASE.md from release/0.2.z in the main branch.

docs: RELEASE.md add note about branches for trustify-ui

---

migration/src/lib.rs
migration/src/m0000920_perf_indexes.rs

During ingestion, do we do clean up descriptions using:
```sql
DELETE FROM "vulnerability_description" WHERE "vulnerability_description"."advisory_id" = $1
```
That shows up in the AWS RDS console as top SQL statement. I think an index might help. But I am guessing.

chore: add index for DELETE operation

---

Cargo.lock
common/Cargo.toml
common/src/config.rs
common/src/db/mod.rs
docs/env-vars.md

exposing some of sea_orm database conn configurations (as per https://docs.rs/sea-orm/latest/sea_orm/struct.ConnectOptions.html)
```rust
pub connect_timeout: u64,
#[arg(id="db-acquire-timeout", long, env = ENV_DB_ACQUIRE_TIMEOUT, default_value_t=DB_ACQUIRE_TIMEOUT.into(), conflicts_with = "db-url")]
pub acquire_timeout: u64,
#[arg(id="db-max-lifetime", long, env = ENV_DB_MAX_LIFETIME, default_value_t=DB_MAX_LIFETIME.into(), conflicts_with = "db-url")]
pub max_lifetime: u64,
#[arg(id="db-idle-timeout", long, env = ENV_DB_IDLE_TIMEOUT, default_value_t=DB_IDLE_TIMEOUT.into(), conflicts_with = "db-url")]
pub idle_timeout: u64,
```
doing this will presumably set db conn keepalive settings to avoid having to stand up a tls conn with every db request.
which use …

chore: add db conn env vars

---

entity/src/version_scheme.rs
etc/test-data/cyclonedx/ghsa_test.json
etc/test-data/osv/GHSA-cvw2-xj8r-mjf7.json
modules/fundamental/tests/sbom/details.rs
modules/ingestor/src/service/advisory/osv/loader.rs
modules/ingestor/src/service/advisory/osv/translate.rs

https://issues.redhat.com/browse/TC-2240
During local tests execution (and confirmed from GH CI job), it turned out the [test thread reached its limit](https://github.com/trustification/trustify/actions/runs/13258299168/job/37009027768?pr=1281#step:9:351), i.e. 2 MB, so ~`RUST_MIN_STACK` has been set to 3 MB, referencing it also in the project's README ([preview](https://github.com/mrizzi/trustify/tree/TC-2240?tab=readme-ov-file#tests-execution))~ the test has been "isolated" manually creating the Tokio runtime for the test execution hence no changes are requested to anyone (neither contributors nor CI jobs).

TC-2240 OSV GHSA - Ecosystem RubyGems

---

etc/datasets/Makefile
etc/datasets/README.md
etc/datasets/ds4.yaml

This PR creates a way to create a new dataset (with db dump) with the following data:
* Red Hat SBOMs
* CVEs since 2020
* GHSA since 2020
* Red Hat CSAF since 2020
This dataset can be used as a lighter and more diverse one for load testing and also a end-to-end testing.
It also provides a way to create an archive with only SBOMs from DS3. It can be very handy during testing. We should enhance SBOM importer to support git as a source, which would make this process easier (#1310)

feat: introduce new dataset (ds4)

---

modules/fundamental/tests/sbom/details.rs

Raising the stack size for the `test_sbom_details_cyclonedx_osv` after the failure in https://github.com/trustification/trustify/actions/runs/13417116433/job/37482008830#step:9:708

fix: test_sbom_details_cyclonedx_osv set thread_stack_size

---

modules/fundamental/Cargo.toml
modules/fundamental/benches/bench-format.rs

This is more focused on our tests and to help to investigate something with [jsn sync](https://github.com/trustification/trustify/blob/a090bf872a4e6670f74bdd65d2ac4f5e04a8b185/modules/ingestor/src/service/format.rs#L248) function.
Sending this PR now to share the code first.
`cargo bench --bench bench-format`

chore: adds a new criterion bench

---

.github/workflows/openapi.yaml

With this PR:
- openapi.yaml from `main` branch will be push to the `main` branch of the ui repository
- openapi.yaml from `release/0.2.z` branch will be push to the `release/0.2.z` branch of the ui repository
This PR will need to be backported to the release/0.2.z branch in this repository and I will take care of it once this PR is merged

ci: allow workflow openapi.yaml to support release/0.2.z

---

.github/scripts/Containerfile.xtask

```console
➜  scripts git:(xtask-bug) ✗ podman run localhost/test-xtask generate-dump
2025-02-24T14:18:32.460442Z  INFO bootstrap: database "test" does not exist, skipping database=Database { url: None, username: "postgres", password: "trustify", host: "localhost", port: 34461, name: "test", max_conn: 75, min_conn: 25, sslmode: Prefer, connect_timeout: 8, acquire_timeout: 8, max_lifetime: 7200, idle_timeout: 600 }
2025-02-24T14:18:32.460497Z  INFO bootstrap: summary="DROP DATABASE IF EXISTS …" db.statement="\n\nDROP DATABASE IF EXISTS \"test\";\n" rows_affected=0 rows_returned=0 elapsed=853.207µs elapsed_secs=0.000853207 database=Database { url: None, username: "postgres", password: "trustify", host: "localhost", port: 34461, name: "test", max_conn: 75, min_conn: 25, sslmode: Prefer, …
```

fix: permission problem with containerized xtask dump

---

Cargo.lock
Cargo.toml
etc/test-data/cyclonedx/broken-refs.json
modules/fundamental/tests/sbom/cyclonedx/corner_cases.rs
modules/fundamental/tests/sbom/cyclonedx/mod.rs
modules/fundamental/tests/sbom/spdx.rs
modules/ingestor/src/graph/sbom/common/relationship.rs
modules/ingestor/src/graph/sbom/cyclonedx.rs
modules/ingestor/src/service/sbom/cyclonedx.rs

This allows to catch some errors, which might lead to internal errors. Instead of failing with a DB error, we now return a more user friendly explanation of what went wrong. We also return warnings, if they don't prevent the ingestion of the document.
Closes: #551

fix(sbom): validate CDX files during ingestion

---

.github/scripts/Containerfile.xtask

The rationale behind that is, that we do create a dump with xtask, which we then upload to S3. Instead of having two pods run, and orchestrating a handover between those two, we simply install the AWS CLI into the image, so that we can use the S3 client.

build: add the AWS client to the xtask image

---

common/src/db/query.rs
common/src/db/query/value.rs
modules/analysis/src/service/mod.rs

Fixes #1280
This introduces a new variant of `Value` that may be used to apply queries to local structs containing _arrays_ of queryable terms.

fix: find analysis components by q=purl

---

etc/test-data/cyclonedx/simple-ext-a.json
modules/analysis/src/endpoints/test.rs
modules/analysis/src/service/collector.rs
modules/analysis/src/service/test.rs
modules/fundamental/tests/sbom/cyclonedx/external/mod.rs

Fixed external sbom cdx test - uncommented test and tightened them using the handy `response.contains_subset(json!({` idiom.

fix: external sbom cdx example and tightened related tests

---

docs/book/modules/admin/examples/trustify/database.tf

Before this change, we did check for the internal subnet by filtering for kubernetes.io/role/internal-elb having an empty value. That worked for cluster we set up in the past. However, it looks like newer clusters to have a value of "1" for this tag. This might come from openshift installers of a newer version.
As we don't require a specific value, but only look for the existence of the tag, this change perform this change. Allowing both variants.

fix(terraform): only ensure the tag exists, don't require a value

---

etc/datasets/ds3/csaf/2024/cve-2024-28834.json
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/sbom/service/sbom.rs
modules/fundamental/src/vulnerability/model/mod.rs
modules/fundamental/tests/dataset.rs

This PR improves fetching vulnerabilities for SBOM, by improving two things:
- Pre-selecting CPEs related to the SBOM and using them in a query. This significantly improves the performance of the query in large datasets.
- Fetching missing data directly in the query, instead of running separate queries in the post-query loop. Querying things in the loop can be costly when dealing with large number of rows. This is now done for advisory issuer organisation and vulnerability description.
With these two changes the speed of the endpoint for ds4 on a laptop is increased tenfold
```
before
________________________________________________________
Executed in  276.15 secs    fish           external
usr time    3.24 secs    0.10 millis    3.24 secs
sys time    0.42 secs    1.36 millis    0.42 …
```

fix: improve performance of sbom/advisory endpoint

---

etc/test-data/cyclonedx/rh/image_index_variants/example_container_index.json
etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_arm64.json
etc/test-data/cyclonedx/rh/image_index_variants/imageindex_quarkus_mandrel.json
etc/test-data/cyclonedx/rh/image_index_variants/imagevariant_quarkus_mandrel_amd64.json
etc/test-data/cyclonedx/rh/image_index_variants/imagevariant_quarkus_mandrel_arm64.json
modules/analysis/src/endpoints/tests/rh_variant.rs
modules/analysis/src/service/collector.rs
modules/analysis/src/service/mod.rs
modules/ingestor/src/graph/sbom/processor/rh_prod_comp.rs

RH imagevariants are a bit 'special' as they currently do not encode **checksum** natively in spdx/cdx ... opting to set _version=sha256###############_. 
This means that we have to handle (for now) with alternate heuristics for determining their relationships.
fixes #1392
**Note: In the future we may remove this special case if/when rh imagevariant start denoting checksums**

fix: imageindex>imagevariant external sboms

---

migration/src/lib.rs
migration/src/m0000030_perf_adv_vuln.rs

This PR helps speed up _api/v2/advisory_ and _api/v2/vulnerability_ endpoints.
After applying this it is good to run:
```sql
VACUUM ANALYZE;
REINDEX database trustify;
```
to start at theoretical baseline performance.

perf: advisory and vuln endpoints

---

migration/src/lib.rs
migration/src/m0000050_perf_adv_vuln2.rs

This PR should help advisory/vuln endpoints by enabling some pg functions to run in parallel. Also a few key indexes are added.

perf: change cvss related pg funcs to immutable parallel safe and a few key indexes

---

migration/src/lib.rs
migration/src/m0000060_perf_adv_vuln3.rs

This PR changes version related pg funcs to IMMUTABLE PARALLEL SAFE
final fixes #1298

perf: change version related pg funcs to IMMUTABLE PARALLEL SAFE

---

common/src/purl.rs
entity/src/qualified_purl.rs
modules/fundamental/src/license/service/license_export.rs
modules/fundamental/src/purl/model/summary/purl.rs
modules/fundamental/src/purl/service/mod.rs
modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/sbom/service/sbom.rs
modules/fundamental/src/vulnerability/model/details/vulnerability_advisory.rs

Instead of using the three PURL layers (base, version, qualifier) for building result PURLs, we only use the `purl` field from the qualified result, and evaluate the rest inline.
The allows us to reduce load on the database even more. I'll run a scale-test next.

refactor: remove three later PURL processing in more places

---

migration/src/lib.rs
migration/src/m0000070_perf_adv_vuln4.rs

The `advisory_vulnerability_vulnerability_id_gist` considerably slows down `sbom/{id}/advisory` endpoint. Let's disable it for now, until we can further investigate it.

perf: drop advisory_vulnerability_vulnerability_id_gist index for now

---

modules/fundamental/src/ai/service/tools/package_info.rs
modules/fundamental/src/error.rs
modules/fundamental/src/purl/endpoints/mod.rs
modules/fundamental/src/purl/endpoints/test.rs
modules/fundamental/src/purl/model/details/purl.rs
modules/fundamental/src/purl/service/mod.rs
modules/fundamental/src/purl/service/test.rs
modules/fundamental/src/vulnerability/service/test.rs
modules/fundamental/tests/advisory/csaf/delete.rs
modules/fundamental/tests/advisory/csaf/reingest.rs
modules/fundamental/tests/advisory/osv/reingest.rs
openapi.yaml

Allow retrieving multiple PurlDetails by either purl or uuid
Fix #1425

feat: add endpoint to process multiple purls

---

Cargo.lock
common/Cargo.toml
common/src/cpe.rs
common/src/db/query.rs
common/src/db/query/columns.rs
common/src/db/query/filter.rs
common/src/db/query/value.rs
common/src/purl.rs
entity/src/qualified_purl.rs
modules/analysis/src/endpoints/tests/mod.rs
modules/analysis/src/service/load.rs
modules/analysis/src/service/mod.rs

Fixes: #1280
Added the proper logic to translate CPE queries into their constituent columns and Purl queries into comparisons against the `get_purl()` proc, which stringifies the associated JSON blob in the database.
This accounts for the loading of the graph. The fact that both `Cpe` and `Purl` structs now implement Valuable accounts for querying the graph, i.e. applying the query to a context constructed from the graph.

feat: filter components by partial matches of a purl and/or cpe

---

migration/src/m0000010_init_up.sql

account for null namespace when textifying a qualified purl

---

migration/src/m0000010_init_up.sql

fixes #1447
This reverts commit 5e1075324e8821c8a636725c7da004127882cd2f.

Revert "account for null namespace when textifying a qualified purl"

---

etc/deploy/compose/compose.yaml

Unless this hurts a local setup, I'd like to have this enabled by default.

feat: add pg_stats to the compose database

---

modules/fundamental/src/vulnerability/endpoints/mod.rs
modules/fundamental/src/vulnerability/model/mod.rs
modules/fundamental/src/vulnerability/service/mod.rs
modules/fundamental/src/vulnerability/service/test.rs
openapi.yaml

Fix #1449 
The proposed solution evaluates if the provided purls are within the range of the vulnerable versions available in the database.
It returns a HashMap where the key is the purl and the value is a Vector containing the vulnerabilities.
Drop endpoint added it #1425 because it is not needed from any client and this endpoint implements what the other endpoint was meant for.

feat: add analyze endpoint for purl-based vulnerability scan

---

common/src/purl.rs
modules/ingestor/src/graph/sbom/clearly_defined.rs
modules/ingestor/src/service/advisory/cve/divination.rs
modules/ingestor/src/service/advisory/osv/loader.rs

Also added a with_version() helper to avoid some mutability. I'd like to hide all the public fields at some point, as their pub-ness still allows improper encoding, but that's a bigger change.

fix: purl components now properly encoded in Display impl

---

e2e/ds3.hurl
etc/datasets/ds3/cve/2024/CVE-2024-1300.json
etc/datasets/ds3/cve/2024/CVE-2024-1726.json
etc/datasets/ds3/cve/2024/CVE-2024-28834.json
etc/datasets/ds3/cve/2024/CVE-2024-50602.json
modules/fundamental/tests/dataset.rs
modules/ingestor/src/service/advisory/cve/loader.rs

Fixes #1495
I opted for a simple `starts_with` check instead of using BCP47 parser, as it would work anyways for the non standard `en_US` cases. We can improve this in the future if needed.
I also added missing CVE files for DS3

fix: set title for vunerabilities with non typical description language code

---

modules/analysis/src/endpoints/tests/rh_variant.rs
modules/analysis/src/service/mod.rs

Load/ingestion order should not have any impact on analysis graph descendent queries. Also had to fix related tests.
fixes #1509

fix: ensure load order does not impact analysis graph dependency queries

---

etc/test-data/cyclonedx/rh/image_index_variants/example_container_index.json
etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_amd64.json
etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_arm64.json
etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_ppc.json
etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_s390x.json
etc/test-data/cyclonedx/rh/image_index_variants/imageindex_quarkus_mandrel.json
etc/test-data/cyclonedx/rh/image_index_variants/imagevariant_quarkus_mandrel_amd64.json
etc/test-data/cyclonedx/rh/image_index_variants/imagevariant_quarkus_mandrel_arm64.json
modules/analysis/src/endpoints/tests/rh_variant.rs
modules/analysis/src/service/collector.rs
modules/analysis/src/service/mod.rs

Now that rh imageindex>imagevariant encodes sha256 hashes, we can remove custom codepath. fixes #1459

chore: remove imageindex>imagevariant custom codepath.

---

migration/src/lib.rs
migration/src/m0001020_alter_pythonver_cmp.rs
migration/src/m0001020_alter_pythonver_cmp_fns/pythonver_cmp_down.sql
migration/src/m0001020_alter_pythonver_cmp_fns/pythonver_cmp_up.sql
modules/ingestor/tests/version/pythonver.rs

Current implementation didn't properly handled local version of python packages, like `pkg:pypi/torch@2.0.1+cu118`
https://peps.python.org/pep-0440/#local-version-identifiers
I think we need more work on this function to handle all the possible cases, but I'll raise a separate issue for that.

fix: pythonver_cmp function to properly handle local versions

---

Cargo.lock
Cargo.toml
common/auth/src/authenticator/mod.rs
modules/analysis/src/endpoints/tests/cyclonedx.rs
modules/analysis/src/endpoints/tests/spdx.rs
modules/fundamental/src/advisory/endpoints/test.rs
modules/fundamental/src/organization/endpoints/test.rs
modules/fundamental/src/product/endpoints/test.rs
modules/ingestor/src/service/mod.rs
modules/ingestor/src/service/sbom/clearly_defined.rs

BREAKING-CHANGE: The upgraded parser aligns with RFC 9535, and not longer supports the `$.[]` notation. It must be converted into `$[]`. This is important for the group extraction with OIDC, specifically with AWS Cognito.

refactor: Update jsonpath parser library

---

etc/telemetry/config-otel-tempo.yaml
etc/telemetry/config.yaml

level detailed was useful during development but is causing span drops
I wasn't caring about this warning:
```
2025-04-07T19:01:33.028587Z  WARN
get:fetch_vulnerability:from_entity:from_entities:from_query_result:from_query_result_multi_model:
opentelemetry_sdk:  name="BatchSpanProcessor.SpanDroppingStarted"
BatchSpanProcessor dropped a Span due to queue full/internal errors. No
further internal log will be emitted for further drops until Shutdown.
During Shutdown time, a log will be emitted with exact count of total
Spans dropped.
```
Until notice the difference of half the spans being dropped

chore: lowered otel-collector logs

---

docs/book/modules/admin/pages/infrastructure.adoc

https://issues.redhat.com/browse/TC-2332
---
Currently the setup of keycloack is executed with the helm chart https://github.com/trustification/trustify-helm-charts/tree/main/charts/trustify-infrastructure/templates/keycloak or in the compose file https://github.com/trustification/trustify/tree/main/etc/deploy/compose/config/init-sso but we haven't a doc like the v1 https://github.com/trustification/trustification/blob/main/docs/modules/admin/pages/cluster-preparing.adoc#keycloak to explain to the customer that don't use compose or helm-chart how to setup keycloak to be usable with Ansible on Rhel without OCP/AWS
For Cognito instead we have a section of the doc https://github.com/trustification/trustify/blob/5e1075324e8821c8a636725c7da004127882cd2f/docs/book/modules/admin/pages/infrastruct …

[TC-2332] Keycloak section

---

migration/src/lib.rs
migration/src/m0001030_perf_adv_gin_index.rs
migration/src/m0001030_perf_adv_gin_index/advisory_identifier_version_document_id_title.sql
modules/fundamental/src/advisory/service/mod.rs

https://issues.redhat.com/browse/TC-2428
within the context of the advisory search:
- the columns from the `advisory` table have been added to a `gin` index to improve search performances
- the digests columns from `source_document` table have been removed to make the execution plan more reliable

perf: TC-2428 add gin index to advisory

---

modules/fundamental/src/sbom/endpoints/mod.rs
modules/fundamental/tests/sbom/cyclonedx/corner_cases.rs
modules/fundamental/tests/sbom/cyclonedx/mod.rs
modules/fundamental/tests/sbom/spdx.rs
modules/fundamental/tests/sbom/spdx/corner_cases.rs
modules/ingestor/src/graph/sbom/cyclonedx.rs
modules/ingestor/src/graph/sbom/spdx.rs
modules/ingestor/src/service/mod.rs
modules/ingestor/src/service/sbom/cyclonedx.rs
openapi.yaml

When a document contains invalid references (or other validation errors)
we reject the content. However, returning 500 (or any 5xx) is not
correct. It's a client error (4xx) and the best match seems 400.

fix: return 400 instead of 500 in case of validation errors

---

.github/workflows/scale-test.yaml

Based upon https://github.com/trustification/trustify-load-test-runs/pull/9 for working with the PR number which is retrieved from `github.event.issue.number` as reported in https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only

fix: scale test references the PR number

---

migration/src/lib.rs
migration/src/m0001040_alter_pythonver_cmp.rs
migration/src/m0001040_alter_pythonver_cmp_fns/pythonver_cmp_down.sql
migration/src/m0001040_alter_pythonver_cmp_fns/pythonver_cmp_up.sql
modules/ingestor/tests/version/pythonver.rs

https://issues.redhat.com/browse/TC-2469
[PEP-0440](https://peps.python.org/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions) allowed a more permissive convention for pre-release versions allowing to have a `-` between the version and the pre-release marker, e.g. `1.2.3-rc0`.
So the regex to retrieve the `{left,right}_pre{_num}` fields have been updated consistently and three tests to cover this scenario has been added swapping left and right in order to ensure the same patterns are applied to both left and right fields.

fix: Python versions PLSQL comparator (TC-2469)

---

modules/fundamental/tests/sbom/issue_1535.rs
modules/fundamental/tests/sbom/mod.rs

This is the panic we see when using serde_yml for this specific case:
```
failures:
sbom::issue_1535::not_really_clearly_defined
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 68
filtered out; finished in 4.51s
──── STDERR:             trustify-module-fundamental::fundamental
sbom::issue_1535::not_really_clearly_defined
thread 'sbom::issue_1535::not_really_clearly_defined' panicked at
/home/heliofrota/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f
/libyml-0.0.5/src/scanner.rs:2798:17:
String join would overflow memory bounds
note: run with `RUST_BACKTRACE=1` environment variable to display
a backtrace
Cancelling due to test failure
────────────
Summary [   4.526s] 1 test run: 0 passed, 1 failed, 422
skipped
FAIL [   4.517s]
trustify-module-fundamental::fundamental …
```

test: test reproducing the issue 1535

---

modules/fundamental/src/sbom/model/details.rs
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/sbom/model/raw_sql.rs

This PR refactors SBOM/advisory correlation logic to correctly filter all SBOM-related CPEs in the query, moving it from the post-query loop.
This helps the performance by properly and early selecting statuses that are only related to the SBOM in question. It should lead to much less rows pulled from the database and filtered later (which is one of the problems with large SBOMs).
It also makes this code a bit more maintainable and suitable for future refactoring.
It still doesn't solve all performance issue with the endpoint. RHOSE-4.14 SBOM doesn't fail for me any more locally, but it still take a few minutes (That's why I didn't include load test yet). I don't expect it to have impact on other endpoints.
This is a first step toward performance of SBOM correlation logic for large SBOMs.

refactor: move advisory status cpe filtering to the queries

---

e2e/ds3.hurl
migration/src/lib.rs
migration/src/m0001050_foreign_key_cascade.rs
modules/fundamental/src/advisory/service/mod.rs
modules/fundamental/src/sbom/service/sbom.rs

When deleting an entity (advisory or sbom), the source document is left in the database. This makes uploading the same file again (after deleting) fails.
This PR fixes this. And additionally adds foreign keys to the CVSS tables to clean them as well after deleting an advisory.

fix: when deleting an entity, delete also a source document

---

.github/workflows/backport.yaml

This PR should connect this repository to the release-tools cherry-pick automation across branches.
Generally speaking this is how it should work:
- Every PR that needs to be backport its changes to another branch e.g. `release/0.2.z.` needs to have a label indicating the desire to do so. 
Setting this PR as draft just because I'd like double-check the status of the release-tools repository. And set exact instructions and avoid confusion

ci: add branch cherry-pick automation

---

migration/src/lib.rs
migration/src/m0001060_advisory_vulnerability_indexes.rs

The gist index on advisory_vulnerability(vulnerability_id) slows down significantly (4-5x) any join with that table on vulnerability_id. The database chooses to use gist index over btree one no matter what I tried.
As a result the correlating advisories with a large SBOM is now much faster (e.g. 260s -> 60s). It's still not great, but it's a big improvement.
On the other hand I don't see slowdown in other endpoints when this index is dropped. I don't think we ever directly search this table.

fix: remove advisory_vulnerability gist index

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
common/src/hashing.rs
etc/deploy/compose/.gitignore
etc/deploy/compose/compose-minio.yaml
modules/ingestor/src/service/dataset/mod.rs
modules/ingestor/src/service/mod.rs
modules/storage/Cargo.toml
modules/storage/src/config.rs
modules/storage/src/service/compression/mod.rs
modules/storage/src/service/dispatch.rs
modules/storage/src/service/fs.rs
modules/storage/src/service/mod.rs
modules/storage/src/service/s3.rs
modules/storage/src/service/temp.rs
modules/storage/src/service/test.rs

Rewrite S3 storage using AWS S3 SDK. Properly handling the head request, if the key is not found.
Currently blocked by: https://github.com/awslabs/aws-sdk-rust/issues/1281

fix: support custom trust anchors, fix a "not found" issue

---

.github/workflows/backport.yaml

The main branch backport.yaml workflow requires the appropriate label to be added before the PR is merged.
If for any reason we forgot to add the label and we still need to backport a PR after it has been merged then:
- Add the appropriate label to indicate to which branch we need to backport
- Add a comment with `/backport` and it should trigger a backport even though the PR has been merged already.
Since the PR has been merged already hence CLOSED I think it is better for the user to make a conscious decision typing `/backport` to trigger a backport

ci: allow backports with comments

---

etc/test-data/cve/CVE-1999-0001.json
modules/fundamental/src/advisory/endpoints/test.rs
modules/fundamental/src/advisory/model/details/advisory_vulnerability.rs
openapi.yaml

fix: show null severity in vulnerability when it's null in advisory

---

entity/src/labels.rs
modules/fundamental/README.md
modules/fundamental/src/advisory/endpoints/label.rs
modules/fundamental/src/advisory/endpoints/test.rs
modules/fundamental/src/sbom/endpoints/label.rs
modules/fundamental/src/sbom/endpoints/test.rs
modules/fundamental/src/test/label.rs
modules/fundamental/src/test/mod.rs
modules/importer/src/runner/clearly_defined_curation/mod.rs
modules/importer/src/runner/csaf/storage.rs
modules/importer/src/runner/cve/mod.rs
modules/importer/src/runner/osv/mod.rs
modules/importer/src/runner/sbom/storage.rs
openapi.yaml

While documenting some examples, I noted that tags with empty values are a problem when patch-updating. Fixing that, adding tests, align tests between sbom and advisories. And give some examples.

chore: clean up labels API, add tests, handle removing, add docs

---

modules/analysis/src/endpoints/tests/latest_filters.rs
modules/analysis/src/service/load.rs
modules/analysis/src/service/mod.rs

fixes #1559 because the previous q= query was a hack (against node_id) and middleware sboms dont generate spdx ids in the same way (so we could no longer 'cheat').
* optimised some analysis graph latest queries using postgres **PARTITION_BY**
* latest queries ensures only the sboms that are needed are loaded into analysis graph
* converted sql into sea_orm so we can use trustify query capabilities
* fixed some tests

fix: ensure middleware sboms work with analysis graph and optimise graph cache

---

common/src/db/query.rs
common/src/db/query/columns.rs
common/src/db/query/filtering.rs
common/src/db/query/sort.rs
modules/fundamental/src/advisory/service/mod.rs
modules/fundamental/src/sbom/endpoints/test.rs
modules/fundamental/src/vulnerability/service/mod.rs

Tonight's performance regression seems to be cause by #1585:
```
HEAD: 
3: test                 
1: logon               |        6.90 |          6 |           9 |          7
2: search_advisory     |        4919 |      4,769 |       5,173 |      4,769
minus b27418b4306f458e23665c70869a1b19ae1abd99,d914a349bc2342ad2f659c5c370f903561acf2d6:
3: test                 
1: logon               |        6.98 |          6 |          17 |          7
2: search_advisory     |      301.93 |        193 |         460 |        300
```

Revert #1585

---

modules/fundamental/src/purl/service/gc_purls.sql
modules/fundamental/src/purl/service/test.rs

Note: This does not address the performance issue described in https://github.com/trustification/trustify/issues/1589, but the duplication still needed to be resolved.

fix: remove duplicate UNION in gc_purls SELECT

---

modules/fundamental/src/lib.rs
modules/fundamental/src/vulnerability/endpoints/mod.rs
modules/fundamental/src/vulnerability/endpoints/test.rs
openapi.yaml

Backport of #1619 to `release/0.2.z`.

chore: deprecate vulnerability delete endpoint (TC-2519) [Backport release/0.2.z]

---

modules/fundamental/src/ai/service/tools/cve_info.rs
modules/fundamental/src/purl/endpoints/test.rs
modules/ingestor/src/service/advisory/cve/loader.rs

This PR fixes #1239
The CVSS v3.0 and v3.1 scores are now parsed from cve files and stored in the database.

feat: parse and store cvss3 scores for cve files

---

modules/fundamental/src/purl/service/gc_purls.sql

Fixes #1589 
```
2025-05-19T11:40:16.267101Z  INFO ThreadId(01) actix_server::server: Tokio runtime found; starting in existing Tokio runtime
2025-05-19T11:40:16.267113Z  INFO ThreadId(01) actix_server::server: starting service: "actix-web-service-[::1]:8080", workers: 12, listening on: [::1]:8080
2025-05-19T11:43:38.203811Z  WARN ThreadId(30) gc_purls: sqlx::query: slow statement: execution time exceeded alert threshold summary="WITH alive_qualified_purl AS ( …" db.statement="\n\nWITH\n    alive_qualified_purl AS (\n        SELECT DISTINCT t2.id, t2.versioned_purl_id\n        FROM sbom_package_purl_ref AS t1\n                 INNER JOIN qualified_purl AS t2\n                            ON t2.id = t1.qualified_purl_id\n    ),\n    alive_versioned_purl AS (\n        SELECT DISTINCT t2.id, …
```

fix: delete advisory performance

---

etc/telemetry/config-otel-tempo.yaml
etc/telemetry/config.yaml

chore: ignore spans shorter than 1ms

---

docs/adrs/00004-advisory-scores.md

This PR contains ADR for handling vulnerability scores and severities. It covers current state of things in specs that we are using and proposing API changes to properly reflect data that users are interested in.

doc: adr for handling vulnerability scores and severities

---

docs/adrs/00005-ui-upload.md

Also see: https://issues.redhat.com/browse/TC-2298

docs: ADR for an upload API targeted towards the browser

---

entity/src/cvss3.rs
entity/src/vulnerability.rs
etc/test-data/cve/CVE-2023-20862.json
etc/test-data/cve/CVE-2023-39325.json
etc/test-data/cve/CVE-2023-39326.json
etc/test-data/cve/CVE-2023-42282.json
etc/test-data/cve/CVE-2023-44487.json
migration/src/lib.rs
migration/src/m0001070_vulnerability_scores.rs
migration/src/m0001070_vulnerability_scores.sql
modules/fundamental/src/advisory/model/details/advisory_vulnerability.rs
modules/fundamental/src/ai/service/tools/cve_info.rs
modules/fundamental/src/purl/model/details/purl.rs
modules/fundamental/src/vulnerability/endpoints/test.rs
modules/fundamental/src/vulnerability/model/details/mod.rs
modules/fundamental/src/vulnerability/model/summary.rs
modules/fundamental/src/vulnerability/service/mod.rs
modules/fundamental/src/vulnerability/service/test.rs
modules/graphql/src/vulnerability.rs
modules/ingestor/src/graph/vulnerability/mod.rs
modules/ingestor/src/service/advisory/cve/loader.rs

This PR changes how vulnerability scoring is set. Instead of calculating an average
from all advisories, it is now parsed from the CVE file. The score and severity values
are stored in the vulnerability database.
I tried at first looking for an cve advisory and retrieving the value, but the query gets even more complicated and slow than calculating an average. And as it is the integral part of the vulnerability, I think the value belongs in the table.
With this PR I didn't change the current API, so it's still called `average_score` and `average_severity`. I will tackle that in a separate PR (I need to think of how deprecating current values will work).
The search query is changed though. Please see the comment below for the details.

fix: set vulnerability score from cve advisory

---

Cargo.toml
entity/Cargo.toml
entity/src/advisory.rs
entity/src/cvss3.rs
entity/src/labels.rs
entity/src/organization.rs
entity/src/sbom.rs
entity/src/vulnerability.rs
modules/fundamental/Cargo.toml
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/vulnerability/model/mod.rs
modules/graphql/Cargo.toml
server/Cargo.toml
server/src/openapi.rs
server/src/profile/api.rs
server/src/profile/importer.rs

This adds a feature for graphql logic and dependencies. Reducing the number of dependencies when not using graphql, which is the default at the moment.
Removing a bunch of dependencies:
```
3d2
< actix_derive v0.6.2
13d11
< actix-web-actors v4.3.1+deprecated
37d34
< ascii_utils v0.9.3
39d35
< async-channel v2.3.1
42,46d37
< async-graphql-actix-web v7.0.16
< async-graphql-derive v7.0.16
< async-graphql-parser v7.0.16
< async-graphql v7.0.16
< async-graphql-value v7.0.16
208d198
< event-listener-strategy v0.5.4
212d201
< fast_chemail v0.9.6
255d243
< handlebars v5.1.2
369d356
< multer v3.1.0
461d447
< proc-macro-crate v3.3.0
588d573
< static_assertions_next v1.1.2
638,639d622
< toml_datetime v0.6.9
< toml_edit v0.22.26
660d642
< trustify-module-graphql v0.2.19
716d697
< winnow v0.7.10
```

build: add feature flag for graphql

---

Cargo.toml
entity/Cargo.toml
entity/src/advisory.rs
entity/src/cvss3.rs
entity/src/labels.rs
entity/src/organization.rs
entity/src/sbom.rs
entity/src/vulnerability.rs
modules/fundamental/Cargo.toml
modules/fundamental/src/sbom/model/mod.rs
modules/fundamental/src/vulnerability/model/mod.rs
modules/graphql/Cargo.toml
server/Cargo.toml
server/src/openapi.rs
server/src/profile/api.rs
server/src/profile/importer.rs

This adds a feature for graphql logic and dependencies. Reducing the number of dependencies when not using graphql, which is the default at the moment.
Backport https://github.com/trustification/trustify/pull/1679 to `release/0.3.z`.

build: add feature flag for graphql [Backport release/0.3.z]

---

Cargo.lock
server/src/profile/api.rs

Related to https://github.com/trustification/trustify-ui/pull/498
The UI repository removed the `analytics` option as it was never used nor implemented.
Originally it was supposed to be used for Segment.io analytics due to v1 compatibility. But it was decided that it was not needed and removed from the requirements. So it never worked.
This PR removes the `analytics` parameters passed to the UI and point to the latest available UI version in the main branch.

task: align UI removal of Analytics prop

---

Cargo.lock
server/src/profile/api.rs

Backport of https://github.com/trustification/trustify/pull/1699 to `release/0.3.z`.
- The auto Cherry-pick failed therefore I created the backport manually
- Also this PR points to the latest commit in the UI branch `release/0.3.z`

task: align UI removal of Analytics prop [Backport release/0.3.z]

---

common/src/db/embedded.rs

There was a typo in the fix in https://github.com/trustification/trustify/pull/1691 so env variable name doesn't match the one set up

fix: env variable name typo

---

common/src/db/query/columns.rs
modules/fundamental/src/sbom/endpoints/test.rs

Relates #1652
Specifically, affirming these do the right thing:
- `labels:type=spdx&labels:type=cyclonedx`
- `labels:type!=spdx&labels:type!=cyclonedx`
- `labels:type!=spdx|cyclonedx`
- `labels:type=spdx|cyclonedx`

Add some more unit tests around label queries

---

codecov.yml

We get the benefit of the report without the annoyance of a failed build.

ci: set non-blocking codecov status checks

---

Cargo.lock
Cargo.toml
etc/test-data/cve/CVE-2017-20197.json
etc/test-data/cve/CVE-2024-7826.json
modules/fundamental/src/vulnerability/service/test.rs
modules/ingestor/src/service/advisory/cve/loader.rs

Currently we only extract base score and severity values. There's need to be more work done to properly save all scores of all versions for vulnerabilities and advisories. The base score used for the vulnerability will be picked from the highest cvss version available. Since base severity was not standardized in cvss v2.0 it is recalculated from the score.

feat: start exctracting vulnerability scores from cvss v4 and v2

---

codecov.yml

This reverts commit 1bb18f5e712c9eb7d56ee901b5e28d1eebd39489.
As discussed in today's handover call with @PhilipCattanach, this will be reverted. The check was never blocking anything, just reporting. Furthermore, such PRs should be discussed first.

Revert "ci: set non-blocking codecov status checks (#1725)"

---

modules/analysis/src/service/collector.rs
modules/analysis/src/service/mod.rs

Having the `graphs` variable logged dumps out an enormous amount of data, not adding any value. Blocking the log file, having an impact on performance.
I believe this has an impact on: https://issues.redhat.com/browse/TC-2567

fix: prevent dumping massive amounts of log info

---

etc/telemetry/compose.yaml
etc/telemetry/config-collector.yaml

Long story... to summarize, and without pointing to upstream OTEL PRs.. 
* They have this page where they are keeping updates related to the collector's internal telemetry:
https://opentelemetry.io/docs/collector/internal-telemetry/
* I used this to ensure that my node.js example was sending traces and that those were being received by the collector:
https://github.com/obs-nebula/check-traces/tree/main/scripts
* They changed things and will continue changing, since some parts are still marked as [alpha].
* These changes don't impact our dev env (compose.yaml workflow etc), but:
* During development, if I see that `otelcol_receiver_accepted_metric_points` and/or `otelcol_receiver_accepted_spans` are greater than zero, it means traces and metrics are being sent to the collector without need …

chore: otelcol internal telemetry

---

Cargo.lock
modules/analysis/Cargo.toml
modules/analysis/src/model/graph.rs
modules/analysis/src/service/collector.rs
modules/analysis/src/service/load.rs
modules/analysis/src/service/mod.rs
modules/analysis/src/service/test.rs

Using non-string types and interning strings results in around ~15% less memory usage of the cache:
Before:
```json
[
{
"edges": 67665,
"nodes": 62888,
"sbom_id": "0195bae4-1d7b-7591-8564-2c635b272d80",
"size": 56543379,
"size_human": "53.9 MiB"
},
{
"edges": 82240,
"nodes": 65647,
"sbom_id": "0195bae3-0629-74b0-ad5b-82f184882e71",
"size": 54225990,
"size_human": "51.7 MiB"
},
{
"edges": 38711,
"nodes": 20147,
"sbom_id": "0195baf0-9534-7132-be80-55fd926a6b52",
"size": 15488838,
"size_human": "14.8 MiB"
},
{
"edges": 76008,
"nodes": 68337,
"sbom_id": "0195bae4-6fc9-7ac0-9e1e-7459211ae095",
"size": 61641210,
"size_human": "58.8 MiB"
},
{
"edges": 111086,
"nodes": 81906,
"sbom_id": "0195bae2-2edd-7f21-929e-c23fb2eb54bb",
"size": 66205830,
"size_human": "63.1 MiB"
}
]
```
After:
```json
[
{ …
```

feat(analysis): reduce memory consumption by 10-15%

---

entity/src/sbom_node.rs
etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_amd64.json
etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_arm64.json
etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_ppc.json
etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_s390x.json
etc/test-data/cyclonedx/rh/image_index_variants/imagevariant_quarkus_mandrel_amd64.json
etc/test-data/cyclonedx/rh/image_index_variants/imagevariant_quarkus_mandrel_arm64.json
etc/test-data/cyclonedx/rh/latest_filters/TC-2606/401A4500E49D44D.json
etc/test-data/cyclonedx/rh/latest_filters/TC-2606/74092FCBFD294FC.json
etc/test-data/cyclonedx/rh/latest_filters/TC-2606/80138DC9368C4D3.json
etc/test-data/cyclonedx/rh/latest_filters/TC-2606/B67E38F00200413.json
etc/test-data/cyclonedx/rh/latest_filters/TC-2606/CE8E7B92C4BD452.json
modules/analysis/src/endpoints/tests/latest_filters.rs
modules/analysis/src/endpoints/tests/rh_variant.rs
modules/analysis/src/service/load.rs
modules/analysis/src/service/mod.rs

There were a few issues here to fix:
(fixes TC-2606)

fix: ensure latest cpe query returns latest roots

---

.github/workflows/backport.yaml

Reusable workflow call is done by using `uses` and `runs-on` isn't allowed so I'm removing it (ref. https://docs.github.com/en/actions/sharing-automations/reusing-workflows#calling-a-reusable-workflow)

fix: remove 'runs-on' from 'backport' CI job

---

etc/test-data/osv/GHSA-69ch-w2m2-3vjp.json
etc/test-data/osv/GHSA-ppp9-7jff-5vj2.json
migration/src/lib.rs
migration/src/m0001130_gover_cmp.rs
migration/src/m0001130_gover_cmp_fns/gover_cmp_down.sql
migration/src/m0001130_gover_cmp_fns/gover_cmp_up.sql
modules/fundamental/src/vulnerability/service/test.rs

Go ecosystem often uses 'v' prefix before semver formatted versions
https://go.dev/ref/mod#versions
On the other hand, OSV and other adivsories are reporting pure semver versions. Newly introduced golang_version_matches pgsql function, strips the prefix if it is present and then continues with semver match.

fix: add support for golang versions with 'v' prefix

---

Cargo.lock
modules/fundamental/src/vulnerability/service/mod.rs
modules/fundamental/tests/dataset.rs
modules/fundamental/tests/fundamental.rs
modules/fundamental/tests/vuln/mod.rs
test-context/Cargo.toml
test-context/src/lib.rs

For one, this adds more instrumentation in places where it seems to make sense.
Second, this makes it easier for tests to run tests based on a dataset by providing out of the box functionality to ingest a dataset.

chore: more instrumentation and refactor dataset tests

---

modules/analysis/src/endpoints/tests/latest_filters.rs
modules/analysis/src/service/load.rs

When using **/latest/** endpoint with _?q=_ or exact name queries we cannot directly rank off component name.

fix: narrow latest search when using q= or name
